[DIFFICULTY_NORMAL][0] =
{
    .trainerName = _("Test1"),
    .trainerClass = TRAINER_CLASS_PKMN_TRAINER_1,
    .trainerPic = TRAINER_PIC_RED,
    .encounterMusic_gender = TRAINER_ENCOUNTER_MUSIC_MALE,
    .doubleBattle = FALSE,
    .partySize = 3,
    .party = (const struct TrainerMon[])
    {
        {
        .lvl = 67,
        .species = SPECIES_WOBBUFFET,
        .ability = ABILITY_TELEPATHY,
        .nature = NATURE_HASTY,
        .ev = TRAINER_PARTY_EVS(252, 0, 0, 252, 4, 0), //EV_SPREAD_X
        .iv = TRAINER_PARTY_IVS(25, 26, 27, 28, 29, 30), //IVS(X)
        .moves = {MOVE_AIR_SLASH, MOVE_BARRIER, MOVE_SOLAR_BEAM, MOVE_EXPLOSION},
        .gender = TRAINER_MON_FEMALE,
        .heldItem = ITEM_ASSAULT_VEST,
        .ball = ITEM_MASTER_BALL,
        .isShiny = TRUE,
        .nickname = COMPOUND_STRING("Bubbles"),
        .friendship = 42,
        .useGimmick = GIMMICK_DYNAMAX,
        .dynamaxLevel = 5,
        .shouldDynamax = TRUE,
        },
        {
        .lvl = 5,
        .species = SPECIES_WOBBUFFET,
        .ability = ABILITY_SHADOW_TAG,
        },
        {
        .species = SPECIES_WYNAUT,
        .lvl = 5,
        },
    },
},
[DIFFICULTY_NORMAL][1] =
{
    .trainerName = _("Test2"),
    .trainerClass = TRAINER_CLASS_PKMN_TRAINER_1,
    .trainerPic = TRAINER_PIC_RED,
    .encounterMusic_gender =
        TRAINER_ENCOUNTER_MUSIC_MALE,
    .doubleBattle = FALSE,
    .partySize = 1,
    .party = (const struct TrainerMon[])
    {
        {
        .species = SPECIES_MEWTWO,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 5,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        },
    },
},
[DIFFICULTY_NORMAL][2] =
{
    {
        {
        .species = SPECIES_MEWTWO,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 50,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        },
    },
},
[DIFFICULTY_EASY][2] =
{
    {
        {
        .species = SPECIES_METAPOD,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 1,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        },
    },
},
[DIFFICULTY_HARD][2] =
{
    {
        {
        .species = SPECIES_ARCEUS,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 99,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        },
    },
},
[DIFFICULTY_NORMAL][3] =
{
    .trainerName = _("Test3"),
    .trainerClass = TRAINER_CLASS_PKMN_TRAINER_1,
    .trainerPic = TRAINER_PIC_RED,
    .encounterMusic_gender =
        TRAINER_ENCOUNTER_MUSIC_MALE,
    .doubleBattle = FALSE,
    .partySize = 1,
    .poolSize = 4,
    .party = (const struct TrainerMon[])
    {
        {
        .species = SPECIES_WYNAUT,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        },
        {
        .species = SPECIES_WOBBUFFET,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        },
        {
        .species = SPECIES_EEVEE,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        },
        {
        .species = SPECIES_MEW,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        },
    },
},
[DIFFICULTY_NORMAL][4] =
{
    .trainerName = _("Test4"),
    .trainerClass = TRAINER_CLASS_PKMN_TRAINER_1,
    .trainerPic = TRAINER_PIC_RED,
    .encounterMusic_gender =
        TRAINER_ENCOUNTER_MUSIC_MALE,
    .doubleBattle = FALSE,
    .partySize = 3,
    .poolSize = 6,
    .party = (const struct TrainerMon[])
    {
        {
        .species = SPECIES_WYNAUT,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        },
        {
        .species = SPECIES_WOBBUFFET,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        .tags = MON_POOL_TAG_LEAD,
        },
        {
        .species = SPECIES_EEVEE,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        .tags = MON_POOL_TAG_ACE,
        },
        {
        .species = SPECIES_MEW,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        },
        {
        .species = SPECIES_ODDISH,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        .tags = MON_POOL_TAG_ACE,
        },
        {
        .species = SPECIES_ARON,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        .tags = MON_POOL_TAG_LEAD,
        },
    },
},
[DIFFICULTY_NORMAL][5] =
{
    .trainerName = _("Test5"),
    .trainerClass = TRAINER_CLASS_PKMN_TRAINER_1,
    .trainerPic = TRAINER_PIC_RED,
    .encounterMusic_gender =
        TRAINER_ENCOUNTER_MUSIC_MALE,
    .doubleBattle = TRUE,
    .poolRuleIndex = POOL_RULESET_WEATHER_DOUBLES,
    .partySize = 3,
    .poolSize = 10,
    .party = (const struct TrainerMon[])
    {
        {
        .species = SPECIES_WYNAUT,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        .tags = MON_POOL_TAG_LEAD,
        },
        {
        .species = SPECIES_WOBBUFFET,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        .tags = MON_POOL_TAG_LEAD,
        },
        {
        .species = SPECIES_VULPIX,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        .tags = MON_POOL_TAG_LEAD | MON_POOL_TAG_WEATHER_SETTER,
        },
        {
        .species = SPECIES_BULBASAUR,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        .tags = MON_POOL_TAG_LEAD | MON_POOL_TAG_WEATHER_ABUSER,
        },
        {
        .species = SPECIES_TORKOAL,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        .tags = MON_POOL_TAG_LEAD | MON_POOL_TAG_WEATHER_SETTER,
        },
        {
        .species = SPECIES_CHERRIM,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        .tags = MON_POOL_TAG_LEAD | MON_POOL_TAG_WEATHER_ABUSER,
        },
        {
        .species = SPECIES_MEW,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        .tags = MON_POOL_TAG_LEAD,
        },
        {
        .species = SPECIES_ARON,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        .tags = MON_POOL_TAG_LEAD,
        },
        {
        .species = SPECIES_ODDISH,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        },
        {
        .species = SPECIES_EEVEE,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        },
    },
},
[DIFFICULTY_NORMAL][6] =
{
    .trainerName = _("Test6"),
    .trainerClass = TRAINER_CLASS_PKMN_TRAINER_1,
    .trainerPic = TRAINER_PIC_RED,
    .encounterMusic_gender =
        TRAINER_ENCOUNTER_MUSIC_MALE,
    .doubleBattle = FALSE,
    .poolRuleIndex = POOL_RULESET_BASIC,
    .partySize = 2,
    .poolSize = 3,
    .party = (const struct TrainerMon[])
    {
        {
        .species = SPECIES_WYNAUT,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        .tags = MON_POOL_TAG_LEAD,
        },
        {
        .species = SPECIES_WOBBUFFET,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        .tags = MON_POOL_TAG_LEAD,
        },
        {
        .species = SPECIES_EEVEE,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        .tags = MON_POOL_TAG_LEAD,
        },
    },
},
[DIFFICULTY_NORMAL][7] =
{
    .trainerName = _("Test1"),
    .trainerClass = TRAINER_CLASS_PKMN_TRAINER_1,
    .trainerPic = TRAINER_PIC_RED,
    .encounterMusic_gender =
        TRAINER_ENCOUNTER_MUSIC_MALE,
    .doubleBattle = FALSE,
    .poolRuleIndex = POOL_RULESET_BASIC,
    .poolPruneIndex = POOL_PRUNE_TEST,
    .partySize = 2,
    .poolSize = 3,
    .party = (const struct TrainerMon[])
    {
        {
        .species = SPECIES_WYNAUT,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        },
        {
        .species = SPECIES_WOBBUFFET,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        .tags = MON_POOL_TAG_LEAD,
        },
        {
        .species = SPECIES_EEVEE,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        },
    },
},
[DIFFICULTY_NORMAL][8] =
{
    .trainerName = _("Test1"),
    .trainerClass = TRAINER_CLASS_PKMN_TRAINER_1,
    .trainerPic = TRAINER_PIC_RED,
    .encounterMusic_gender =
        TRAINER_ENCOUNTER_MUSIC_MALE,
    .doubleBattle = FALSE,
    .poolRuleIndex = POOL_RULESET_BASIC,
    .poolPickIndex = POOL_PICK_LOWEST,
    .partySize = 2,
    .poolSize = 3,
    .party = (const struct TrainerMon[])
    {
        {
        .species = SPECIES_WYNAUT,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        .tags = MON_POOL_TAG_ACE,
        },
        {
        .species = SPECIES_WOBBUFFET,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        },
        {
        .species = SPECIES_EEVEE,
        .gender = TRAINER_MON_RANDOM_GENDER,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .lvl = 100,
        .nature = NATURE_HARDY,
        .dynamaxLevel = MAX_DYNAMAX_LEVEL,
        .tags = MON_POOL_TAG_LEAD,
        },
    },
},
