#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#include "constants/battle_partner.h"
#define TRAINER_NONE                        0
#define TRAINER_BRENDAN_ROUTE_103_GRASS     1
#define TRAINER_BRENDAN_RUSTBORO_GRASS      2
#define TRAINER_BRENDAN_ROUTE_110_GRASS     3
#define TRAINER_BRENDAN_ROUTE_119_GRASS     4
#define TRAINER_BRENDAN_LILYCOVE_GRASS      5
#define TRAINER_BRENDAN_ROUTE_103_FIRE      6
#define TRAINER_BRENDAN_RUSTBORO_FIRE       7
#define TRAINER_BRENDAN_ROUTE_110_FIRE      8
#define TRAINER_BRENDAN_ROUTE_119_FIRE      9
#define TRAINER_BRENDAN_LILYCOVE_FIRE      10
#define TRAINER_BRENDAN_ROUTE_103_WATER    11
#define TRAINER_BRENDAN_RUSTBORO_WATER     12
#define TRAINER_BRENDAN_ROUTE_110_WATER    13
#define TRAINER_BRENDAN_ROUTE_119_WATER    14
#define TRAINER_BRENDAN_LILYCOVE_WATER     15
#define TRAINER_MAY_ROUTE_103_GRASS        16
#define TRAINER_MAY_RUSTBORO_GRASS         17
#define TRAINER_MAY_ROUTE_110_GRASS        18
#define TRAINER_MAY_ROUTE_119_GRASS        19
#define TRAINER_MAY_LILYCOVE_GRASS         20
#define TRAINER_MAY_ROUTE_103_FIRE         21
#define TRAINER_MAY_RUSTBORO_FIRE          22
#define TRAINER_MAY_ROUTE_110_FIRE         23
#define TRAINER_MAY_ROUTE_119_FIRE         24
#define TRAINER_MAY_LILYCOVE_FIRE          25
#define TRAINER_MAY_ROUTE_103_WATER        26
#define TRAINER_MAY_RUSTBORO_WATER         27
#define TRAINER_MAY_ROUTE_110_WATER        28
#define TRAINER_MAY_ROUTE_119_WATER        29
#define TRAINER_MAY_LILYCOVE_WATER         30
#define TRAINER_WALLY_MAUVILLE             31
#define TRAINER_WALLY_VERDANTURF           32
#define TRAINER_WALLY_ROUTE_114            33
#define TRAINER_WALLY_VICTORY_ROAD_1       34
#define TRAINER_WALLY_VICTORY_ROAD_2       35
#define TRAINER_WALLY_VICTORY_ROAD_3       36
#define TRAINER_WALLY_VICTORY_ROAD_4       37
#define TRAINER_WALLY_VICTORY_ROAD_5       38
#define TRAINER_ROXANNE_1                  39
#define TRAINER_ROXANNE_2                  40
#define TRAINER_ROXANNE_3                  41
#define TRAINER_ROXANNE_4                  42
#define TRAINER_ROXANNE_5                  43
#define TRAINER_BRAWLY_1                   44
#define TRAINER_BRAWLY_2                   45
#define TRAINER_BRAWLY_3                   46
#define TRAINER_BRAWLY_4                   47
#define TRAINER_BRAWLY_5                   48
#define TRAINER_WATTSON_1                  49
#define TRAINER_WATTSON_2                  50
#define TRAINER_WATTSON_3                  51
#define TRAINER_WATTSON_4                  52
#define TRAINER_WATTSON_5                  53
#define TRAINER_FLANNERY_1                 54
#define TRAINER_FLANNERY_2                 55
#define TRAINER_FLANNERY_3                 56
#define TRAINER_FLANNERY_4                 57
#define TRAINER_FLANNERY_5                 58
#define TRAINER_NORMAN_1                   59
#define TRAINER_NORMAN_2                   60
#define TRAINER_NORMAN_3                   61
#define TRAINER_NORMAN_4                   62
#define TRAINER_NORMAN_5                   63
#define TRAINER_WINONA_1                   64
#define TRAINER_WINONA_2                   65
#define TRAINER_WINONA_3                   66
#define TRAINER_WINONA_4                   67
#define TRAINER_WINONA_5                   68
#define TRAINER_TATE_AND_LIZA_1            69
#define TRAINER_TATE_AND_LIZA_2            70
#define TRAINER_TATE_AND_LIZA_3            71
#define TRAINER_TATE_AND_LIZA_4            72
#define TRAINER_TATE_AND_LIZA_5            73
#define TRAINER_JUAN_1                     74
#define TRAINER_JUAN_2                     75
#define TRAINER_JUAN_3                     76
#define TRAINER_JUAN_4                     77
#define TRAINER_JUAN_5                     78
#define TRAINER_SIDNEY                     79
#define TRAINER_SIDNEY_REMATCH             80
#define TRAINER_PHOEBE                     81
#define TRAINER_PHOEBE_REMATCH             82
#define TRAINER_GLACIA                     83
#define TRAINER_GLACIA_REMATCH             84
#define TRAINER_DRAKE                      85
#define TRAINER_DRAKE_REMATCH              86
#define TRAINER_WALLACE                    87
#define TRAINER_WALLACE_REMATCH            88
#define TRAINER_STEVEN                     89
#define TRAINER_GABBY_AND_TY_1             90
#define TRAINER_GABBY_AND_TY_2             91
#define TRAINER_GABBY_AND_TY_3             92
#define TRAINER_GABBY_AND_TY_4             93
#define TRAINER_GABBY_AND_TY_5             94
#define TRAINER_GABBY_AND_TY_6             95
//Route 102
#define TRAINER_CALVIN_1                   96
#define TRAINER_CALVIN_2                   97
#define TRAINER_CALVIN_3                   98
#define TRAINER_CALVIN_4                   99
#define TRAINER_CALVIN_5                  100
#define TRAINER_RICK                      101
#define TRAINER_ALLEN                     102
#define TRAINER_TIANA                     103
//Route 104 (south)
#define TRAINER_WINSTON_1                 104
#define TRAINER_WINSTON_2                 105
#define TRAINER_WINSTON_3                 106
#define TRAINER_WINSTON_4                 107
#define TRAINER_WINSTON_5                 108
#define TRAINER_BILLY                     109
#define TRAINER_DARIAN                    110
//Petalburg Woods
#define TRAINER_LYLE                      111
#define TRAINER_CASPIAN_PETALBURG_WOODS   112
#define TRAINER_JAMES_1                   113
#define TRAINER_JAMES_2                   114
#define TRAINER_JAMES_3                   115
#define TRAINER_JAMES_4                   116
#define TRAINER_JAMES_5                   117
//Route 104 (north)
#define TRAINER_CINDY_1                   118
#define TRAINER_CINDY_2                   119
#define TRAINER_CINDY_3                   120
#define TRAINER_CINDY_4                   121
#define TRAINER_CINDY_5                   122
#define TRAINER_HALEY_1                   123
#define TRAINER_HALEY_2                   124
#define TRAINER_HALEY_3                   125
#define TRAINER_HALEY_4                   126
#define TRAINER_HALEY_5                   127
#define TRAINER_GINA_AND_MIA              128
#define TRAINER_IVAN                      129
//Route 116
#define TRAINER_JOSE                      130
#define TRAINER_JOEY                      131
#define TRAINER_JANICE                    132
#define TRAINER_CLARK                     133
#define TRAINER_DEVAN                     134
#define TRAINER_JOHNSON                   135
#define TRAINER_DAWSON                    136
#define TRAINER_SARAH                     137
#define TRAINER_JERRY_1                   138
#define TRAINER_JERRY_2                   139
#define TRAINER_JERRY_3                   140
#define TRAINER_JERRY_4                   141
#define TRAINER_JERRY_5                   142
#define TRAINER_KAREN_1                   143
#define TRAINER_KAREN_2                   144
#define TRAINER_KAREN_3                   145
#define TRAINER_KAREN_4                   146
#define TRAINER_KAREN_5                   147
//Rustboro Gym
#define TRAINER_JOSH                      148
#define TRAINER_TOMMY                     149
#define TRAINER_MARC                      150
//Rusturf Tunnel
#define TRAINER_CASPIAN_RUSTURF_TUNNEL    151
//Route 106 (land)
#define TRAINER_NED                       152
#define TRAINER_ELLIOT_1                  153
#define TRAINER_ELLIOT_2                  154
#define TRAINER_ELLIOT_3                  155
#define TRAINER_ELLIOT_4                  156
#define TRAINER_ELLIOT_5                  157
//Dewford Gym
#define TRAINER_LAURA                     158
#define TRAINER_LILITH                    159
#define TRAINER_BRENDEN                   160
#define TRAINER_TAKAO                     161
#define TRAINER_CRISTIAN                  162
#define TRAINER_JOCELYN                   163
//Route 109 (land)
#define TRAINER_HUEY                      164
#define TRAINER_EDMOND                    165
#define TRAINER_HAILEY                    166
#define TRAINER_CHANDLER                  167
#define TRAINER_LOLA_1                    168
#define TRAINER_LOLA_2                    169
#define TRAINER_LOLA_3                    170
#define TRAINER_LOLA_4                    171
#define TRAINER_LOLA_5                    172
#define TRAINER_RICKY_1                   173
#define TRAINER_RICKY_2                   174
#define TRAINER_RICKY_3                   175
#define TRAINER_RICKY_4                   176
#define TRAINER_RICKY_5                   177
//Seashore House
#define TRAINER_SIMON                     178
#define TRAINER_JOHANNA                   179
#define TRAINER_DWAYNE                    180
//Oceanic Museum
#define TRAINER_MALIK_MUSEUM              181
#define TRAINER_MARINA_MUSEUM             182
#define TRAINER_ARCHIE_MUSEUM             183
//Route 110
#define TRAINER_ISABEL_1                  184
#define TRAINER_ISABEL_2                  185
#define TRAINER_ISABEL_3                  186
#define TRAINER_ISABEL_4                  187
#define TRAINER_ISABEL_5                  188
#define TRAINER_KALEB                     189
//Trick House 1
#define TRAINER_SALLY                     190
#define TRAINER_ROBIN                     191
#define TRAINER_EDDIE                     192
//Route 103
#define TRAINER_DAISY                     193
#define TRAINER_MARCOS                    194
#define TRAINER_RHETT                     195
#define TRAINER_AMY_AND_LIV_1             196
#define TRAINER_AMY_AND_LIV_2             197
#define TRAINER_AMY_AND_LIV_3             198
#define TRAINER_AMY_AND_LIV_4             199
#define TRAINER_AMY_AND_LIV_5             200
#define TRAINER_MIGUEL_1                  201
#define TRAINER_MIGUEL_2                  202
#define TRAINER_MIGUEL_3                  203
#define TRAINER_MIGUEL_4                  204
#define TRAINER_MIGUEL_5                  205
#define TRAINER_ANDREW                    206
//Route 110
#define TRAINER_TIMMY                     207
#define TRAINER_EDWIN_1                   208
#define TRAINER_EDWIN_2                   209
#define TRAINER_EDWIN_3                   210
#define TRAINER_EDWIN_4                   211
#define TRAINER_EDWIN_5                   212
#define TRAINER_JOSEPH                    213
#define TRAINER_EDWARD                    214
#define TRAINER_ALYSSA                    215
#define TRAINER_DALE                      216
//Route 117
#define TRAINER_DYLAN_1                   217
#define TRAINER_DYLAN_2                   218
#define TRAINER_DYLAN_3                   219
#define TRAINER_DYLAN_4                   220
#define TRAINER_DYLAN_5                   221
#define TRAINER_MARIA_1                   222
#define TRAINER_MARIA_2                   223
#define TRAINER_MARIA_3                   224
#define TRAINER_MARIA_4                   225
#define TRAINER_MARIA_5                   226
#define TRAINER_ISAAC_1                   227
#define TRAINER_ISAAC_2                   228
#define TRAINER_ISAAC_3                   229
#define TRAINER_ISAAC_4                   230
#define TRAINER_ISAAC_5                   231
#define TRAINER_LYDIA_1                   232
#define TRAINER_LYDIA_2                   233
#define TRAINER_LYDIA_3                   234
#define TRAINER_LYDIA_4                   235
#define TRAINER_LYDIA_5                   236
#define TRAINER_ANNA_AND_MEG_1            237
#define TRAINER_ANNA_AND_MEG_2            238
#define TRAINER_ANNA_AND_MEG_3            239
#define TRAINER_ANNA_AND_MEG_4            240
#define TRAINER_ANNA_AND_MEG_5            241
#define TRAINER_DEREK                     242
#define TRAINER_BRANDI                    243
#define TRAINER_MELINA                    244
#define TRAINER_AISHA                     245
//Rusturf Tunnel
#define TRAINER_MIKE                      246
//Mauville Gym
#define TRAINER_VIVIAN                    247
#define TRAINER_KIRK                      248
#define TRAINER_BEN                       249
#define TRAINER_ANGELO                    250
#define TRAINER_SHAWN                     251
//Route 118 (west)
#define TRAINER_ROSE_1                    252
#define TRAINER_ROSE_2                    253
#define TRAINER_ROSE_3                    254
#define TRAINER_ROSE_4                    255
#define TRAINER_ROSE_5                    256
#define TRAINER_DEANDRE                   257
#define TRAINER_DALTON_1                  258
#define TRAINER_DALTON_2                  259
#define TRAINER_DALTON_3                  260
#define TRAINER_DALTON_4                  261
#define TRAINER_DALTON_5                  262
#define TRAINER_WADE                      263
//Cycling Road
#define TRAINER_JACLYN                    264
#define TRAINER_ABIGAIL_1                 265
#define TRAINER_ABIGAIL_2                 266
#define TRAINER_ABIGAIL_3                 267
#define TRAINER_ABIGAIL_4                 268
#define TRAINER_ABIGAIL_5                 269
#define TRAINER_BENJAMIN_1                270
#define TRAINER_BENJAMIN_2                271
#define TRAINER_BENJAMIN_3                272
#define TRAINER_BENJAMIN_4                273
#define TRAINER_BENJAMIN_5                274
#define TRAINER_ANTHONY                   275
#define TRAINER_JASMINE                   276
#define TRAINER_JACOB                     277
//Trick House 2
#define TRAINER_TED                       278
#define TRAINER_PAUL                      279
#define TRAINER_GEORGIA                   280
//Route 111 (south)
#define TRAINER_TYRON                     281
#define TRAINER_LILY                      282
#define TRAINER_BIANCA                    283
#define TRAINER_HAYDEN                    284
#define TRAINER_VICTOR                    285
#define TRAINER_VICTORIA                  286
#define TRAINER_VIVI                      287
#define TRAINER_VICKY                     288
#define TRAINER_IRENE                     289
#define TRAINER_TRAVIS                    290
//Route 112
#define TRAINER_LARRY                     291
#define TRAINER_CAROL                     292
#define TRAINER_BRICE                     293
#define TRAINER_TRENT_1                   294
#define TRAINER_TRENT_2                   295
#define TRAINER_TRENT_3                   296
#define TRAINER_TRENT_4                   297
#define TRAINER_TRENT_5                   298
#define TRAINER_BRYANT                    299
#define TRAINER_SHAYLA                    300
//Route 111 north
#define TRAINER_WILTON_1                  301
#define TRAINER_WILTON_2                  302
#define TRAINER_WILTON_3                  303
#define TRAINER_WILTON_4                  304
#define TRAINER_WILTON_5                  305
#define TRAINER_BROOKE_1                  306
#define TRAINER_BROOKE_2                  307
#define TRAINER_BROOKE_3                  308
#define TRAINER_BROOKE_4                  309
#define TRAINER_BROOKE_5                  310
#define TRAINER_DAISUKE                   311
//Route 113
#define TRAINER_JAYLEN                    312
#define TRAINER_LAWRENCE                  313
#define TRAINER_LUNG                      314
#define TRAINER_WYATT                     315
#define TRAINER_MADELINE_1                316
#define TRAINER_MADELINE_2                317
#define TRAINER_MADELINE_3                318
#define TRAINER_MADELINE_4                319
#define TRAINER_MADELINE_5                320
#define TRAINER_TORI_AND_TIA              321
#define TRAINER_LAO_1                     322
#define TRAINER_LAO_2                     323
#define TRAINER_LAO_3                     324
#define TRAINER_LAO_4                     325
#define TRAINER_LAO_5                     326
#define TRAINER_DILLON                    327
#define TRAINER_SOPHIE                    328
#define TRAINER_COBY                      329
//Route 114
#define TRAINER_NOLAN                     330
#define TRAINER_CHARLOTTE                 331
#define TRAINER_KAI                       332
#define TRAINER_CLAUDE                    333
#define TRAINER_NANCY                     334
#define TRAINER_TYRA_AND_IVY              335
#define TRAINER_SHANE                     336
#define TRAINER_STEVE_1                   337
#define TRAINER_STEVE_2                   338
#define TRAINER_STEVE_3                   339
#define TRAINER_STEVE_4                   340
#define TRAINER_STEVE_5                   341
#define TRAINER_BERNIE_1                  342
#define TRAINER_BERNIE_2                  343
#define TRAINER_BERNIE_3                  344
#define TRAINER_BERNIE_4                  345
#define TRAINER_BERNIE_5                  346
#define TRAINER_LUCAS                     347
#define TRAINER_ANGELINA                  348
#define TRAINER_LENNY                     349
//Meteor Falls
#define TRAINER_COURTNEY_METEOR_FALLS     350
//Route 115 (south)
#define TRAINER_NOB_1                     351
#define TRAINER_NOB_2                     352
#define TRAINER_NOB_3                     353
#define TRAINER_NOB_4                     354
#define TRAINER_NOB_5                     355
#define TRAINER_HECTOR                    356
#define TRAINER_MARLENE                   357
#define TRAINER_CYNDY_1                   358
#define TRAINER_CYNDY_2                   359
#define TRAINER_CYNDY_3                   360
#define TRAINER_CYNDY_4                   361
#define TRAINER_CYNDY_5                   362
//Mt. Chimney (Magma)
#define TRAINER_GRUNT_MT_CHIMNEY_1        363
#define TRAINER_GRUNT_MT_CHIMNEY_2        364
#define TRAINER_TABITHA_MT_CHIMNEY        365
#define TRAINER_MAXIE_MT_CHIMNEY          366
//Jagged Pass
#define TRAINER_ERIC                      367
#define TRAINER_GRUNT_JAGGED_PASS         368
#define TRAINER_DIANA_1                   369
#define TRAINER_DIANA_2                   370
#define TRAINER_DIANA_3                   371
#define TRAINER_DIANA_4                   372
#define TRAINER_DIANA_5                   373
#define TRAINER_AUTUMN                    374
#define TRAINER_JULIO                     375
#define TRAINER_ETHAN_1                   376
#define TRAINER_ETHAN_2                   377
#define TRAINER_ETHAN_3                   378
#define TRAINER_ETHAN_4                   379
#define TRAINER_ETHAN_5                   380
//Lavaridge Gym
#define TRAINER_JEFF                      381
#define TRAINER_JACE                      382
#define TRAINER_ELI                       383
#define TRAINER_COLE                      384
#define TRAINER_GERALD                    385
#define TRAINER_AXLE                      386
#define TRAINER_KEEGAN                    387
#define TRAINER_DANIELLE                  388
//Mt. Chimney
#define TRAINER_SHIRLEY                   389
#define TRAINER_SHEILA                    390
#define TRAINER_SHELBY_1                  391
#define TRAINER_SHELBY_2                  392
#define TRAINER_SHELBY_3                  393
#define TRAINER_SHELBY_4                  394
#define TRAINER_SHELBY_5                  395
#define TRAINER_SAWYER_1                  396
#define TRAINER_SAWYER_2                  397
#define TRAINER_SAWYER_3                  398
#define TRAINER_SAWYER_4                  399
#define TRAINER_SAWYER_5                  400
#define TRAINER_MELISSA                   401
//Route 111 (desert)
#define TRAINER_HEIDI                     402
#define TRAINER_BEAU                      403
#define TRAINER_DREW                      404
#define TRAINER_BECKY                     405
#define TRAINER_DUSTY_1                   406
#define TRAINER_DUSTY_2                   407
#define TRAINER_DUSTY_3                   408
#define TRAINER_DUSTY_4                   409
#define TRAINER_DUSTY_5                   410
#define TRAINER_CELIA                     411
#define TRAINER_BRYAN                     412
#define TRAINER_BRANDEN                   413
//Trick House 3
#define TRAINER_JUSTIN                    414
#define TRAINER_MARTHA                    415
#define TRAINER_ALAN                      416
//Petalburg Gym
#define TRAINER_RANDALL                   417
#define TRAINER_MARY                      418
#define TRAINER_PARKER                    419
#define TRAINER_ALEXIA                    420
#define TRAINER_GEORGE                    421
#define TRAINER_JODY                      422
#define TRAINER_BERKE                     423
//Route 103 (water)
#define TRAINER_ISABELLE                  424
#define TRAINER_PETE                      425
//Route 115 (north)
#define TRAINER_JAIDEN                    426
#define TRAINER_TIMOTHY_1                 427
#define TRAINER_TIMOTHY_2                 428
#define TRAINER_TIMOTHY_3                 429
#define TRAINER_TIMOTHY_4                 430
#define TRAINER_TIMOTHY_5                 431
#define TRAINER_KYRA                      432
#define TRAINER_KOICHI                    433
#define TRAINER_HELENE                    434
#define TRAINER_ALIX                      435
//Route 105
#define TRAINER_IMANI                     436
#define TRAINER_DOMINIK                   437
#define TRAINER_FOSTER                    438
#define TRAINER_BEVERLY                   439
#define TRAINER_ANDRES_1                  440
#define TRAINER_ANDRES_2                  441
#define TRAINER_ANDRES_3                  442
#define TRAINER_ANDRES_4                  443
#define TRAINER_ANDRES_5                  444
#define TRAINER_JOSUE                     445
#define TRAINER_LUIS                      446
//Route 106 (water)
#define TRAINER_DOUGLAS                   447
#define TRAINER_KYLA                      448
//Route 107
#define TRAINER_DENISE                    449
#define TRAINER_TONY_1                    450
#define TRAINER_TONY_2                    451
#define TRAINER_TONY_3                    452
#define TRAINER_TONY_4                    453
#define TRAINER_TONY_5                    454
#define TRAINER_LISA_AND_RAY              455
#define TRAINER_DARRIN                    456
#define TRAINER_BETH                      457
#define TRAINER_CAMRON                    458
//Route 108
#define TRAINER_MISSY                     459
#define TRAINER_MATTHEW                   460
#define TRAINER_TARA                      461
#define TRAINER_CAROLINA                  462
#define TRAINER_CORY_1                    463
#define TRAINER_CORY_2                    464
#define TRAINER_CORY_3                    465
#define TRAINER_CORY_4                    466
#define TRAINER_CORY_5                    467
#define TRAINER_JEROME                    468
//Abandoned Ship
#define TRAINER_THALIA_1                  469
#define TRAINER_THALIA_2                  470
#define TRAINER_THALIA_3                  471
#define TRAINER_THALIA_4                  472
#define TRAINER_THALIA_5                  473
#define TRAINER_DEMETRIUS                 474
#define TRAINER_DUNCAN                    475
#define TRAINER_CHARLIE                   476
#define TRAINER_GARRISON                  477
#define TRAINER_JANI                      478
#define TRAINER_KIRA_AND_DAN_1            479
#define TRAINER_KIRA_AND_DAN_2            480
#define TRAINER_KIRA_AND_DAN_3            481
#define TRAINER_KIRA_AND_DAN_4            482
#define TRAINER_KIRA_AND_DAN_5            483
//Route 109 (water)
#define TRAINER_AUSTINA                   484
#define TRAINER_GWEN                      485
#define TRAINER_DAVID                     486
#define TRAINER_ALICE                     487
#define TRAINER_CARTER                    488
#define TRAINER_ELIJAH                    489
#define TRAINER_MEL_AND_PAUL              490
//Trick House 4
#define TRAINER_YUJI                      491
#define TRAINER_CORA                      492
#define TRAINER_PAULA                     493
//Route 118 (east)
#define TRAINER_BARNY                     494
#define TRAINER_CHESTER                   495
#define TRAINER_PERRY                     496
//Route 123 (west)
#define TRAINER_DAVIS                     497
#define TRAINER_JAZMYN                    498
#define TRAINER_VIOLET                    499
#define TRAINER_MIU_AND_YUKI              500
//Route 119 (south)
#define TRAINER_KENT                      501
#define TRAINER_DONALD                    502
#define TRAINER_GREG                      503
#define TRAINER_TAYLOR                    504
#define TRAINER_DOUG                      505
#define TRAINER_BRENT                     506
#define TRAINER_CHRIS                     507
#define TRAINER_CATHERINE_1               508
#define TRAINER_CATHERINE_2               509
#define TRAINER_CATHERINE_3               510
#define TRAINER_CATHERINE_4               511
#define TRAINER_CATHERINE_5               512
#define TRAINER_JACKSON_1                 513
#define TRAINER_JACKSON_2                 514
#define TRAINER_JACKSON_3                 515
#define TRAINER_JACKSON_4                 516
#define TRAINER_JACKSON_5                 517
#define TRAINER_RACHEL                    518
#define TRAINER_PHIL                      519
#define TRAINER_TAKASHI                   520
#define TRAINER_DAYTON                    521
#define TRAINER_HUGH                      522
//Weather Institute
#define TRAINER_GRUNT_WEATHER_INSTITUTE_1 523
#define TRAINER_GRUNT_WEATHER_INSTITUTE_2 524
#define TRAINER_MALIK_WEATHER_INSTITUTE   525
#define TRAINER_MARINA_WEATHER_INSTITUTE  526
#define TRAINER_GRUNT_WEATHER_INSTITUTE_5 527
#define TRAINER_SHELLY_WEATHER_INSTITUTE  528
//Route 119 (north)
#define TRAINER_FABIAN                    529
#define TRAINER_YASU                      530
#define TRAINER_HIDEO                     531
//Route 120 (north)
#define TRAINER_CLARISSA                  532
#define TRAINER_ROBERT_1                  533
#define TRAINER_ROBERT_2                  534
#define TRAINER_ROBERT_3                  535
#define TRAINER_ROBERT_4                  536
#define TRAINER_ROBERT_5                  537
//Fortree Gym
#define TRAINER_HUMBERTO                  538
#define TRAINER_JARED                     539
#define TRAINER_ASHLEY                    540
#define TRAINER_FLINT                     541
#define TRAINER_EDWARDO                   542
#define TRAINER_DARIUS                    543
//Route 120 (south)
#define TRAINER_COLIN                     544
#define TRAINER_LEONEL                    545
#define TRAINER_ANGELICA                  546
#define TRAINER_RILEY                     547
#define TRAINER_CALLIE                    548
#define TRAINER_JENNIFER                  549
#define TRAINER_JENNA                     550
#define TRAINER_LORENZO                   551
#define TRAINER_JEFFREY_1                 552
#define TRAINER_JEFFREY_2                 553
#define TRAINER_JEFFREY_3                 554
#define TRAINER_JEFFREY_4                 555
#define TRAINER_JEFFREY_5                 556
#define TRAINER_KEIGO                     557
#define TRAINER_CHIP                      558
//Route 121
#define TRAINER_CALE                      559
#define TRAINER_TAMMY                     560
#define TRAINER_JESSICA_1                 561
#define TRAINER_JESSICA_2                 562
#define TRAINER_JESSICA_3                 563
#define TRAINER_JESSICA_4                 564
#define TRAINER_JESSICA_5                 565
#define TRAINER_KATE_AND_JOY              566
#define TRAINER_PAT                       567
#define TRAINER_MYLES                     568
#define TRAINER_WALTER_1                  569
#define TRAINER_WALTER_2                  570
#define TRAINER_WALTER_3                  571
#define TRAINER_WALTER_4                  572
#define TRAINER_WALTER_5                  573
#define TRAINER_VANESSA                   574
#define TRAINER_MARCEL                    575
#define TRAINER_CRISTIN_1                 576
#define TRAINER_CRISTIN_2                 577
#define TRAINER_CRISTIN_3                 578
#define TRAINER_CRISTIN_4                 579
#define TRAINER_CRISTIN_5                 580
//Mt. Pyre
#define TRAINER_MARK                      581
#define TRAINER_LEAH                      582
#define TRAINER_ZANDER                    583
#define TRAINER_DEZ_AND_LUKE              584
#define TRAINER_KAYLA                     585
#define TRAINER_GABRIELLE_1               586
#define TRAINER_GABRIELLE_2               587
#define TRAINER_GABRIELLE_3               588
#define TRAINER_GABRIELLE_4               589
#define TRAINER_GABRIELLE_5               590
#define TRAINER_WILLIAM                   591
#define TRAINER_TASHA                     592
#define TRAINER_ATSUSHI                   593
#define TRAINER_VALERIE_1                 594
#define TRAINER_VALERIE_2                 595
#define TRAINER_VALERIE_3                 596
#define TRAINER_VALERIE_4                 597
#define TRAINER_VALERIE_5                 598
#define TRAINER_CEDRIC                    599
#define TRAINER_GRUNT_MT_PYRE_1           600
#define TRAINER_GRUNT_MT_PYRE_2           601
#define TRAINER_MALIK_MT_PYRE             602
#define TRAINER_MARINA_MT_PYRE            603
//Route 123 (east)
#define TRAINER_CAMERON_1                 604
#define TRAINER_CAMERON_2                 605
#define TRAINER_CAMERON_3                 606
#define TRAINER_CAMERON_4                 607
#define TRAINER_CAMERON_5                 608
#define TRAINER_JONAS                     609
#define TRAINER_KAYLEY                    610
#define TRAINER_KINDRA                    611
#define TRAINER_ED                        612
#define TRAINER_WENDY                     613
#define TRAINER_BRAXTON                   614
#define TRAINER_FERNANDO_1                615
#define TRAINER_FERNANDO_2                616
#define TRAINER_FERNANDO_3                617
#define TRAINER_FERNANDO_4                618
#define TRAINER_FERNANDO_5                619
#define TRAINER_ALBERTO                   620
#define TRAINER_JACKI_1                   621
#define TRAINER_JACKI_2                   622
#define TRAINER_JACKI_3                   623
#define TRAINER_JACKI_4                   624
#define TRAINER_JACKI_5                   625
#define TRAINER_FREDRICK                  626
//Magma Hideout
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1     627
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2     628
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3     629
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4     630
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5     631
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6     632
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7     633
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8     634
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9     635
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10    636
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11    637
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12    638
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13    639
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14    640
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15    641
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16    642
#define TRAINER_TABITHA_MAGMA_HIDEOUT     643
#define TRAINER_MAXIE_MAGMA_HIDEOUT       644
//Aqua Hideout
#define TRAINER_GRUNT_AQUA_HIDEOUT_1      645
#define TRAINER_GRUNT_AQUA_HIDEOUT_2      646
#define TRAINER_GRUNT_AQUA_HIDEOUT_3      647
#define TRAINER_GRUNT_AQUA_HIDEOUT_4      648
#define TRAINER_GRUNT_AQUA_HIDEOUT_5      649
#define TRAINER_GRUNT_AQUA_HIDEOUT_6      650
#define TRAINER_MALIK_AQUA_HIDEOUT        651
#define TRAINER_MARINA_AQUA_HIDEOUT       652
#define TRAINER_MATT_AQUA_HIDEOUT         653
//Route 124
#define TRAINER_GRACE                     654
#define TRAINER_DECLAN                    655
#define TRAINER_LILA_AND_ROY_1            656
#define TRAINER_LILA_AND_ROY_2            657
#define TRAINER_LILA_AND_ROY_3            658
#define TRAINER_LILA_AND_ROY_4            659
#define TRAINER_LILA_AND_ROY_5            660
#define TRAINER_SPENCER                   661
#define TRAINER_JENNY_1                   662
#define TRAINER_JENNY_2                   663
#define TRAINER_JENNY_3                   664
#define TRAINER_JENNY_4                   665
#define TRAINER_JENNY_5                   666
#define TRAINER_CHAD                      667
#define TRAINER_ISABELLA                  668
#define TRAINER_ROLAND                    669
//Route 125
#define TRAINER_ERNEST_1                  670
#define TRAINER_ERNEST_2                  671
#define TRAINER_ERNEST_3                  672
#define TRAINER_ERNEST_4                  673
#define TRAINER_ERNEST_5                  674
#define TRAINER_NOLEN                     675
#define TRAINER_SHARON                    676
#define TRAINER_TANYA                     677
#define TRAINER_PRESLEY                   678
#define TRAINER_AURON                     679
#define TRAINER_STAN                      680
#define TRAINER_KIM_AND_IRIS              681
//Mossdeep Gym
#define TRAINER_PRESTON                   682
#define TRAINER_MAURA                     683
#define TRAINER_SAMANTHA                  684
#define TRAINER_BLAKE                     685
#define TRAINER_MACEY                     686
#define TRAINER_CLIFFORD                  687
#define TRAINER_KATHLEEN                  688
#define TRAINER_NICHOLAS                  689
#define TRAINER_NATE                      690
#define TRAINER_VIRGIL                    691
#define TRAINER_SYLVIA                    692
#define TRAINER_HANNAH                    693
//Trick House 6
#define TRAINER_SOPHIA                    694
#define TRAINER_SEBASTIAN                 695
#define TRAINER_BENNY                     696
//Space Center
#define TRAINER_GRUNT_SPACE_CENTER_1      697
#define TRAINER_GRUNT_SPACE_CENTER_2      698
#define TRAINER_GRUNT_SPACE_CENTER_3      699
#define TRAINER_GRUNT_SPACE_CENTER_4      700
#define TRAINER_GRUNT_SPACE_CENTER_5      701
#define TRAINER_GRUNT_SPACE_CENTER_6      702
#define TRAINER_COURTNEY_SPACE_CENTER     703
#define TRAINER_TABITHA_SPACE_CENTER      704
#define TRAINER_MAXIE_SPACE_CENTER        705
//Route 127
#define TRAINER_AIDAN                     706
#define TRAINER_ATHENA                    707
#define TRAINER_JONAH                     708
#define TRAINER_ROGER                     709
#define TRAINER_HENRY                     710
#define TRAINER_CAMDEN                    711
#define TRAINER_KOJI_1                    712
#define TRAINER_KOJI_2                    713
#define TRAINER_KOJI_3                    714
#define TRAINER_KOJI_4                    715
#define TRAINER_KOJI_5                    716
#define TRAINER_DONNY                     717
//Route 126
#define TRAINER_LEONARDO                  718
#define TRAINER_ISOBEL                    719
#define TRAINER_DEAN                      720
#define TRAINER_NIKKI                     721
#define TRAINER_BARRY                     722
#define TRAINER_SIENNA                    723
#define TRAINER_PABLO_1                   724
#define TRAINER_PABLO_2                   725
#define TRAINER_PABLO_3                   726
#define TRAINER_PABLO_4                   727
#define TRAINER_PABLO_5                   728
#define TRAINER_BRENDA                    729
//Route 128
#define TRAINER_RUBEN                     730
#define TRAINER_ALEXA                     731
#define TRAINER_WAYNE                     732
#define TRAINER_ISAIAH_1                  733
#define TRAINER_ISAIAH_2                  734
#define TRAINER_ISAIAH_3                  735
#define TRAINER_ISAIAH_4                  736
#define TRAINER_ISAIAH_5                  737
#define TRAINER_KATELYN_1                 738
#define TRAINER_KATELYN_2                 739
#define TRAINER_KATELYN_3                 740
#define TRAINER_KATELYN_4                 741
#define TRAINER_KATELYN_5                 742
#define TRAINER_CARLEE                    743
#define TRAINER_HARRISON                  744
//Seafloor Cavern
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_1   745
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_2   746
#define TRAINER_MALIK_SEAFLOOR_CAVERN     747
#define TRAINER_MARINA_SEAFLOOR_CAVERN    748
#define TRAINER_MATT_SEAFLOOR_CAVERN      749
#define TRAINER_SHELLY_SEAFLOOR_CAVERN    750
#define TRAINER_ARCHIE_SEAFLOOR_CAVERN    751
//Route 129
#define TRAINER_REED                      752
#define TRAINER_CHASE                     753
#define TRAINER_ALLISON                   754
#define TRAINER_CLARENCE                  755
#define TRAINER_TISHA                     756
//Route 130
#define TRAINER_RODNEY                    757
#define TRAINER_KATIE                     758
#define TRAINER_SANTIAGO                  759
//Route 131
#define TRAINER_KEVIN                     760
#define TRAINER_TALIA                     761
#define TRAINER_RICHARD                   762
#define TRAINER_KARA                      763
#define TRAINER_HERMAN                    764
#define TRAINER_SUSIE                     765
#define TRAINER_RELI_AND_IAN              766
//Route 132
#define TRAINER_GILBERT                   767
#define TRAINER_DANA                      768
#define TRAINER_RONALD                    769
#define TRAINER_KIYO                      770
#define TRAINER_PAXTON                    771
#define TRAINER_DARCY                     772
#define TRAINER_MAKAYLA                   773
#define TRAINER_JONATHAN                  774
//Route 133
#define TRAINER_LINDA                     775
#define TRAINER_BECK                      776
#define TRAINER_CONOR                     777
#define TRAINER_MOLLIE                    778
#define TRAINER_WARREN                    779
#define TRAINER_DEBRA                     780
#define TRAINER_FRANKLIN                  781
//Route 134
#define TRAINER_LAUREL                    782
#define TRAINER_JACK                      783
#define TRAINER_HITOSHI                   784
#define TRAINER_REYNA                     785
#define TRAINER_HUDSON                    786
#define TRAINER_AARON                     787
#define TRAINER_MARLEY                    788
#define TRAINER_ALEX                      789
#define TRAINER_KELVIN                    790
//Sootopolis Gym
#define TRAINER_CONNIE                    791
#define TRAINER_ANDREA                    792
#define TRAINER_DAPHNE                    793
#define TRAINER_ANNIKA                    794
#define TRAINER_TIFFANY                   795
#define TRAINER_CRISSY                    796
#define TRAINER_BETHANY                   797
#define TRAINER_OLIVIA                    798
#define TRAINER_BRIANNA                   799
#define TRAINER_BRIDGET                   800
//Trick House 7
#define TRAINER_JOSHUA                    801
#define TRAINER_PATRICIA                  802
#define TRAINER_MARIELA                   803
#define TRAINER_EVERETT                   804
#define TRAINER_ALEXIS                    805
#define TRAINER_ALVARO                    806
//Meteor Falls (Waterfall)
#define TRAINER_JOHN_AND_JAY_1            807
#define TRAINER_JOHN_AND_JAY_2            808
#define TRAINER_JOHN_AND_JAY_3            809
#define TRAINER_JOHN_AND_JAY_4            810
#define TRAINER_JOHN_AND_JAY_5            811
#define TRAINER_NICOLAS_1                 812
#define TRAINER_NICOLAS_2                 813
#define TRAINER_NICOLAS_3                 814
#define TRAINER_NICOLAS_4                 815
#define TRAINER_NICOLAS_5                 816
//Victory Road
#define TRAINER_ALBERT                    817
#define TRAINER_HOPE                      818
#define TRAINER_SHANNON                   819
#define TRAINER_SAMUEL                    820
#define TRAINER_JULIE                     821
#define TRAINER_OWEN                      822
#define TRAINER_DIANNE                    823
#define TRAINER_FELIX                     824
#define TRAINER_CAROLINE                  825
#define TRAINER_EDGAR                     826
#define TRAINER_MICHELLE                  827
#define TRAINER_MITCHELL                  828
#define TRAINER_HALLE                     829
#define TRAINER_VITO                      830
#define TRAINER_KATELYNN                  831
#define TRAINER_QUINCY                    832
//Trick House 8
#define TRAINER_KEIRA                     833
#define TRAINER_VINCENT                   834
#define TRAINER_LEROY                     835
//S.S. Tidal
#define TRAINER_LEA_AND_JED               836
#define TRAINER_GARRET                    837
#define TRAINER_MICAH                     838
#define TRAINER_COLTON                    839
#define TRAINER_NAOMI                     840
#define TRAINER_THOMAS                    841
#define TRAINER_PHILLIP                   842
#define TRAINER_LEONARD                   843
//Other
#define TRAINER_ANABEL                    844
#define TRAINER_TUCKER                    845
#define TRAINER_SPENSER                   846
#define TRAINER_GRETA                     847
#define TRAINER_NOLAND                    848
#define TRAINER_LUCY                      849
#define TRAINER_BRANDON                   850
#define TRAINER_RED                       851
#define TRAINER_LEAF                      852
#define TRAINER_BRENDAN_PLACEHOLDER       853
#define TRAINER_MAY_PLACEHOLDER           854
#define TRAINER_DUDLEY                    855
#define TRAINER_KAYLEE                    856
#define TRAINER_TERRY                     857
#define TRAINER_UNUSED_1                  858
#define TRAINER_UNUSED_2                  859

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT                      860
#define MAX_TRAINERS_COUNT                  864
#define TRAINER_PARTNER(partner)           (MAX_TRAINERS_COUNT + partner)

#endif  // GUARD_CONSTANTS_OPPONENTS_H
