#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#include "constants/battle_partner.h"
#define TRAINER_NONE                          0
#define TRAINER_BRENDAN_ROUTE_103_MUDKIP      1
#define TRAINER_BRENDAN_RUSTBORO_MUDKIP       2
#define TRAINER_BRENDAN_ROUTE_110_MUDKIP      3
#define TRAINER_BRENDAN_ROUTE_119_MUDKIP      4
#define TRAINER_BRENDAN_LILYCOVE_MUDKIP       5
#define TRAINER_BRENDAN_ROUTE_103_TREECKO     6
#define TRAINER_BRENDAN_RUSTBORO_TREECKO      7
#define TRAINER_BRENDAN_ROUTE_110_TREECKO     8
#define TRAINER_BRENDAN_ROUTE_119_TREECKO     9
#define TRAINER_BRENDAN_LILYCOVE_TREECKO     10
#define TRAINER_BRENDAN_ROUTE_103_TORCHIC    11
#define TRAINER_BRENDAN_RUSTBORO_TORCHIC     12
#define TRAINER_BRENDAN_ROUTE_110_TORCHIC    13
#define TRAINER_BRENDAN_ROUTE_119_TORCHIC    14
#define TRAINER_BRENDAN_LILYCOVE_TORCHIC     15
#define TRAINER_MAY_ROUTE_103_MUDKIP         16
#define TRAINER_MAY_RUSTBORO_MUDKIP          17
#define TRAINER_MAY_ROUTE_110_MUDKIP         18
#define TRAINER_MAY_ROUTE_119_MUDKIP         19
#define TRAINER_MAY_LILYCOVE_MUDKIP          20
#define TRAINER_MAY_ROUTE_103_TREECKO        21
#define TRAINER_MAY_RUSTBORO_TREECKO         22
#define TRAINER_MAY_ROUTE_110_TREECKO        23
#define TRAINER_MAY_ROUTE_119_TREECKO        24
#define TRAINER_MAY_LILYCOVE_TREECKO         25
#define TRAINER_MAY_ROUTE_103_TORCHIC        26
#define TRAINER_MAY_RUSTBORO_TORCHIC         27
#define TRAINER_MAY_ROUTE_110_TORCHIC        28
#define TRAINER_MAY_ROUTE_119_TORCHIC        29
#define TRAINER_MAY_LILYCOVE_TORCHIC         30
#define TRAINER_WALLY_MAUVILLE               31
#define TRAINER_WALLY_VERDANTURF            854
#define TRAINER_WALLY_VR_1                   32
#define TRAINER_WALLY_VR_2                   33
#define TRAINER_WALLY_VR_3                   34
#define TRAINER_WALLY_VR_4                   35
#define TRAINER_WALLY_VR_5                   36
#define TRAINER_ROXANNE_1                    37
#define TRAINER_ROXANNE_2                    38
#define TRAINER_ROXANNE_3                    39
#define TRAINER_ROXANNE_4                    40
#define TRAINER_ROXANNE_5                    41
#define TRAINER_BRAWLY_1                     42
#define TRAINER_BRAWLY_2                     43
#define TRAINER_BRAWLY_3                     44
#define TRAINER_BRAWLY_4                     45
#define TRAINER_BRAWLY_5                     46
#define TRAINER_WATTSON_1                    47
#define TRAINER_WATTSON_2                    48
#define TRAINER_WATTSON_3                    49
#define TRAINER_WATTSON_4                    50
#define TRAINER_WATTSON_5                    51
#define TRAINER_FLANNERY_1                   52
#define TRAINER_FLANNERY_2                   53
#define TRAINER_FLANNERY_3                   54
#define TRAINER_FLANNERY_4                   55
#define TRAINER_FLANNERY_5                   56
#define TRAINER_NORMAN_1                     57
#define TRAINER_NORMAN_2                     58
#define TRAINER_NORMAN_3                     59
#define TRAINER_NORMAN_4                     60
#define TRAINER_NORMAN_5                     61
#define TRAINER_WINONA_1                     62
#define TRAINER_WINONA_2                     63
#define TRAINER_WINONA_3                     64
#define TRAINER_WINONA_4                     65
#define TRAINER_WINONA_5                     66
#define TRAINER_TATE_AND_LIZA_1              67
#define TRAINER_TATE_AND_LIZA_2              68
#define TRAINER_TATE_AND_LIZA_3              69
#define TRAINER_TATE_AND_LIZA_4              70
#define TRAINER_TATE_AND_LIZA_5              71
#define TRAINER_JUAN_1                       72
#define TRAINER_JUAN_2                       73
#define TRAINER_JUAN_3                       74
#define TRAINER_JUAN_4                       75
#define TRAINER_JUAN_5                       76
#define TRAINER_SIDNEY                       77
#define TRAINER_PHOEBE                       78
#define TRAINER_GLACIA                       79
#define TRAINER_DRAKE                        80
#define TRAINER_WALLACE                      81
#define TRAINER_STEVEN                       82
#define TRAINER_GABBY_AND_TY_1               83
#define TRAINER_GABBY_AND_TY_2               84
#define TRAINER_GABBY_AND_TY_3               85
#define TRAINER_GABBY_AND_TY_4               86
#define TRAINER_GABBY_AND_TY_5               87
#define TRAINER_GABBY_AND_TY_6               88
#define TRAINER_CALVIN_1                    387
#define TRAINER_CALVIN_2                    397
#define TRAINER_CALVIN_3                    398
#define TRAINER_CALVIN_4                    399
#define TRAINER_CALVIN_5                    400
#define TRAINER_RICK                        657
#define TRAINER_ALLEN                       402
#define TRAINER_TIANA                       645
#define TRAINER_WINSTON_1                   217
#define TRAINER_WINSTON_2                   220
#define TRAINER_WINSTON_3                   221
#define TRAINER_WINSTON_4                   222
#define TRAINER_WINSTON_5                   223
#define TRAINER_BILLY                       388
#define TRAINER_DARIAN                      725
#define TRAINER_LYLE                        658
#define TRAINER_GRUNT_PETALBURG_WOODS        98
#define TRAINER_JAMES_1                     663
#define TRAINER_JAMES_2                     664
#define TRAINER_JAMES_3                     665
#define TRAINER_JAMES_4                     666
#define TRAINER_JAMES_5                     667
#define TRAINER_CINDY_1                     196
#define TRAINER_CINDY_2                     201
#define TRAINER_CINDY_3                     202
#define TRAINER_CINDY_4                     203
#define TRAINER_CINDY_5                     204
#define TRAINER_HALEY_1                     646
#define TRAINER_HALEY_2                     649
#define TRAINER_HALEY_3                     650
#define TRAINER_HALEY_4                     651
#define TRAINER_HALEY_5                     652
#define TRAINER_GINA_AND_MIA                551
#define TRAINER_IVAN                        405
#define TRAINER_JOSE                        659
#define TRAINER_JOEY                        391
#define TRAINER_JANICE                      647
#define TRAINER_CLARK                       673
#define TRAINER_DEVAN                       782
#define TRAINER_JOHNSON                     783
#define TRAINER_DAWSON                      723
#define TRAINER_SARAH                       724
#define TRAINER_JERRY_1                     342
#define TRAINER_JERRY_2                     345
#define TRAINER_JERRY_3                     346
#define TRAINER_JERRY_4                     347
#define TRAINER_JERRY_5                     348
#define TRAINER_KAREN_1                     349
#define TRAINER_KAREN_2                     351
#define TRAINER_KAREN_3                     352
#define TRAINER_KAREN_4                     353
#define TRAINER_KAREN_5                     354
#define TRAINER_JOSH                        389
#define TRAINER_TOMMY                       390
#define TRAINER_MARC                        617
#define TRAINER_GRUNT_RUSTURF_TUNNEL        104
#define TRAINER_NED                         408
#define TRAINER_ELLIOT_1                    407
#define TRAINER_ELLIOT_2                    414
#define TRAINER_ELLIOT_3                    415
#define TRAINER_ELLIOT_4                    416
#define TRAINER_ELLIOT_5                    417
#define TRAINER_LAURA                       494
#define TRAINER_LILITH                      619
#define TRAINER_BRENDEN                     618
#define TRAINER_TAKAO                       260
#define TRAINER_CRISTIAN                    620
#define TRAINER_JOCELYN                     493
#define TRAINER_HUEY                        556
#define TRAINER_EDMOND                      557
#define TRAINER_HAILEY                      726
#define TRAINER_CHANDLER                    727
#define TRAINER_LOLA_1                      139
#define TRAINER_LOLA_2                      142
#define TRAINER_LOLA_3                      143
#define TRAINER_LOLA_4                      144
#define TRAINER_LOLA_5                      145
#define TRAINER_RICKY_1                     146
#define TRAINER_RICKY_2                     149
#define TRAINER_RICKY_3                     150
#define TRAINER_RICKY_4                     151
#define TRAINER_RICKY_5                     152
#define TRAINER_SIMON                       147
#define TRAINER_JOHANNA                     687
#define TRAINER_DWAYNE                      559
#define TRAINER_GRUNT_MUSEUM_1              108
#define TRAINER_GRUNT_MUSEUM_2              109
#define TRAINER_ISABEL_1                    371
#define TRAINER_ISABEL_2                    372
#define TRAINER_ISABEL_3                    373
#define TRAINER_ISABEL_4                    374
#define TRAINER_ISABEL_5                    375
#define TRAINER_KALEB                       728
#define TRAINER_SALLY                       653
#define TRAINER_ROBIN                       654
#define TRAINER_EDDIE                       401
#define TRAINER_DAISY                       124
#define TRAINER_MARCOS                      731
#define TRAINER_RHETT                       732
#define TRAINER_AMY_AND_LIV_1               549
#define TRAINER_AMY_AND_LIV_2               550
#define TRAINER_AMY_AND_LIV_3               553
#define TRAINER_AMY_AND_LIV_4               554
#define TRAINER_AMY_AND_LIV_5               555
#define TRAINER_MIGUEL_1                    362
#define TRAINER_MIGUEL_2                    364
#define TRAINER_MIGUEL_3                    365
#define TRAINER_MIGUEL_4                    366
#define TRAINER_MIGUEL_5                    367
#define TRAINER_ANDREW                      404
#define TRAINER_TIMMY                       403
#define TRAINER_EDWIN_1                     578
#define TRAINER_EDWIN_2                     581
#define TRAINER_EDWIN_3                     582
#define TRAINER_EDWIN_4                     583
#define TRAINER_EDWIN_5                     584
#define TRAINER_JOSEPH                      729
#define TRAINER_EDWARD                      313
#define TRAINER_ALYSSA                      730
#define TRAINER_DALE                        409
#define TRAINER_DYLAN_1                     432
#define TRAINER_DYLAN_2                     433
#define TRAINER_DYLAN_3                     434
#define TRAINER_DYLAN_4                     435
#define TRAINER_DYLAN_5                     436
#define TRAINER_MARIA_1                     437
#define TRAINER_MARIA_2                     438
#define TRAINER_MARIA_3                     439
#define TRAINER_MARIA_4                     440
#define TRAINER_MARIA_5                     441
#define TRAINER_ISAAC_1                     585
#define TRAINER_ISAAC_2                     588
#define TRAINER_ISAAC_3                     589
#define TRAINER_ISAAC_4                     590
#define TRAINER_ISAAC_5                     591
#define TRAINER_LYDIA_1                     592
#define TRAINER_LYDIA_2                     595
#define TRAINER_LYDIA_3                     596
#define TRAINER_LYDIA_4                     597
#define TRAINER_LYDIA_5                     598
#define TRAINER_ANNA_AND_MEG_1              356
#define TRAINER_ANNA_AND_MEG_2              357
#define TRAINER_ANNA_AND_MEG_3              358
#define TRAINER_ANNA_AND_MEG_4              359
#define TRAINER_ANNA_AND_MEG_5              360
#define TRAINER_DEREK                       308
#define TRAINER_BRANDI                      785
#define TRAINER_MELINA                      784
#define TRAINER_AISHA                       786
#define TRAINER_MIKE                        675
#define TRAINER_VIVIAN                      689
#define TRAINER_KIRK                        272
#define TRAINER_BEN                         392
#define TRAINER_ANGELO                      797
#define TRAINER_SHAWN                       275

#define TRAINER_SAWYER_1                     89
#define TRAINER_SAWYER_2                    830
#define TRAINER_SAWYER_3                    831
#define TRAINER_SAWYER_4                    832
#define TRAINER_SAWYER_5                    833
#define TRAINER_GABRIELLE_1                  97
#define TRAINER_GABRIELLE_2                 834
#define TRAINER_GABRIELLE_3                 835
#define TRAINER_GABRIELLE_4                 836
#define TRAINER_GABRIELLE_5                 837
#define TRAINER_MARCEL                       99
#define TRAINER_ALBERTO                     100
#define TRAINER_ED                          101
#define TRAINER_DECLAN                      103
#define TRAINER_FREDRICK                    117
#define TRAINER_ZANDER                      119
#define TRAINER_ARCHIE                      122
#define TRAINER_LEAH                        123
#define TRAINER_FELIX                       126
#define TRAINER_VIOLET                      127
#define TRAINER_ROSE_1                      125
#define TRAINER_ROSE_2                      128
#define TRAINER_ROSE_3                      129
#define TRAINER_ROSE_4                      130
#define TRAINER_ROSE_5                      131
#define TRAINER_CHIP                        133
#define TRAINER_FOSTER                      134
#define TRAINER_DUSTY_1                     132
#define TRAINER_DUSTY_2                     135
#define TRAINER_DUSTY_3                     136
#define TRAINER_DUSTY_4                     137
#define TRAINER_DUSTY_5                     138
#define TRAINER_AUSTINA                     140
#define TRAINER_GWEN                        141
#define TRAINER_CHARLIE                     148
#define TRAINER_RANDALL                     153
#define TRAINER_PARKER                      154
#define TRAINER_GEORGE                      155
#define TRAINER_BERKE                       156
#define TRAINER_BRAXTON                     157
#define TRAINER_VINCENT                     158
#define TRAINER_LEROY                       159
#define TRAINER_EDGAR                       161
#define TRAINER_ALBERT                      162
#define TRAINER_SAMUEL                      163
#define TRAINER_VITO                        164
#define TRAINER_OWEN                        165
#define TRAINER_WILTON_1                    160
#define TRAINER_WILTON_2                    166
#define TRAINER_WILTON_3                    167
#define TRAINER_WILTON_4                    168
#define TRAINER_WILTON_5                    169
#define TRAINER_WARREN                      170
#define TRAINER_MARY                        171
#define TRAINER_ALEXIA                      172
#define TRAINER_JODY                        173
#define TRAINER_WENDY                       174
#define TRAINER_KEIRA                       175
#define TRAINER_JENNIFER                    177
#define TRAINER_HOPE                        178
#define TRAINER_SHANNON                     179
#define TRAINER_MICHELLE                    180
#define TRAINER_CAROLINE                    181
#define TRAINER_JULIE                       182
#define TRAINER_BROOKE_1                    176
#define TRAINER_BROOKE_2                    183
#define TRAINER_BROOKE_3                    184
#define TRAINER_BROOKE_4                    185
#define TRAINER_BROOKE_5                    186
#define TRAINER_PATRICIA                    187
#define TRAINER_KINDRA                      188
#define TRAINER_TAMMY                       189
#define TRAINER_TASHA                       191
#define TRAINER_VALERIE_1                   190
#define TRAINER_VALERIE_2                   192
#define TRAINER_VALERIE_3                   193
#define TRAINER_VALERIE_4                   194
#define TRAINER_VALERIE_5                   195
#define TRAINER_DAPHNE                      197
#define TRAINER_BRIANNA                     199
#define TRAINER_NAOMI                       200
#define TRAINER_MELISSA                     205
#define TRAINER_SHEILA                      206
#define TRAINER_SHIRLEY                     207
#define TRAINER_CONNIE                      209
#define TRAINER_BRIDGET                     210
#define TRAINER_OLIVIA                      211
#define TRAINER_TIFFANY                     212
#define TRAINER_JESSICA_1                   208
#define TRAINER_JESSICA_2                   213
#define TRAINER_JESSICA_3                   214
#define TRAINER_JESSICA_4                   215
#define TRAINER_JESSICA_5                   216
#define TRAINER_MOLLIE                      218
#define TRAINER_GARRET                      219
#define TRAINER_MARK                        226
#define TRAINER_STEVE_1                     224
#define TRAINER_STEVE_2                     228
#define TRAINER_STEVE_3                     229
#define TRAINER_STEVE_4                     230
#define TRAINER_STEVE_5                     231
#define TRAINER_LUIS                        232
#define TRAINER_DOMINIK                     233
#define TRAINER_DOUGLAS                     234
#define TRAINER_DARRIN                      235
#define TRAINER_JEROME                      237
#define TRAINER_MATTHEW                     238
#define TRAINER_DAVID                       239
#define TRAINER_SPENCER                     240
#define TRAINER_ROLAND                      241
#define TRAINER_NOLEN                       242
#define TRAINER_STAN                        243
#define TRAINER_BARRY                       244
#define TRAINER_DEAN                        245
#define TRAINER_RODNEY                      246
#define TRAINER_RICHARD                     247
#define TRAINER_HERMAN                      248
#define TRAINER_SANTIAGO                    249
#define TRAINER_GILBERT                     250
#define TRAINER_FRANKLIN                    251
#define TRAINER_KEVIN                       252
#define TRAINER_JACK                        253
#define TRAINER_DUDLEY                      254
#define TRAINER_CHAD                        255
#define TRAINER_TONY_1                      236
#define TRAINER_TONY_2                      256
#define TRAINER_TONY_3                      257
#define TRAINER_TONY_4                      258
#define TRAINER_TONY_5                      259
#define TRAINER_HITOSHI                     261
#define TRAINER_KIYO                        262
#define TRAINER_KOICHI                      263
#define TRAINER_NOB_1                       264
#define TRAINER_NOB_2                       265
#define TRAINER_NOB_3                       266
#define TRAINER_NOB_4                       267
#define TRAINER_NOB_5                       268
#define TRAINER_YUJI                        269
#define TRAINER_DAISUKE                     270
#define TRAINER_ATSUSHI                     271
#define TRAINER_DALTON_1                    277
#define TRAINER_DALTON_2                    278
#define TRAINER_DALTON_3                    279
#define TRAINER_DALTON_4                    280
#define TRAINER_DALTON_5                    281
#define TRAINER_COLE                        282
#define TRAINER_JEFF                        283
#define TRAINER_AXLE                        284
#define TRAINER_JACE                        285
#define TRAINER_KEEGAN                      286
#define TRAINER_BERNIE_1                    287
#define TRAINER_BERNIE_2                    288
#define TRAINER_BERNIE_3                    289
#define TRAINER_BERNIE_4                    290
#define TRAINER_BERNIE_5                    291
#define TRAINER_DREW                        292
#define TRAINER_BEAU                        293
#define TRAINER_LARRY                       294
#define TRAINER_SHANE                       295
#define TRAINER_JUSTIN                      296
#define TRAINER_AUTUMN                      298
#define TRAINER_TRAVIS                      299
#define TRAINER_ETHAN_1                     297
#define TRAINER_ETHAN_2                     300
#define TRAINER_ETHAN_3                     301
#define TRAINER_ETHAN_4                     302
#define TRAINER_ETHAN_5                     303
#define TRAINER_BRENT                       304
#define TRAINER_DONALD                      305
#define TRAINER_TAYLOR                      306
#define TRAINER_JEFFREY_1                   307
#define TRAINER_JEFFREY_2                   309
#define TRAINER_JEFFREY_3                   310
#define TRAINER_JEFFREY_4                   311
#define TRAINER_JEFFREY_5                   312
#define TRAINER_PRESTON                     314
#define TRAINER_VIRGIL                      315
#define TRAINER_BLAKE                       316
#define TRAINER_WILLIAM                     317
#define TRAINER_JOSHUA                      318
#define TRAINER_CAMERON_1                   319
#define TRAINER_CAMERON_2                   320
#define TRAINER_CAMERON_3                   321
#define TRAINER_CAMERON_4                   322
#define TRAINER_CAMERON_5                   323
#define TRAINER_JACLYN                      324
#define TRAINER_HANNAH                      325
#define TRAINER_SAMANTHA                    326
#define TRAINER_MAURA                       327
#define TRAINER_KAYLA                       328
#define TRAINER_ALEXIS                      329
#define TRAINER_JACKI_1                     330
#define TRAINER_JACKI_2                     331
#define TRAINER_JACKI_3                     332
#define TRAINER_JACKI_4                     333
#define TRAINER_JACKI_5                     334
#define TRAINER_MICAH                       336
#define TRAINER_THOMAS                      337
#define TRAINER_WALTER_1                    335
#define TRAINER_WALTER_2                    338
#define TRAINER_WALTER_3                    339
#define TRAINER_WALTER_4                    340
#define TRAINER_WALTER_5                    341
#define TRAINER_TED                         343
#define TRAINER_PAUL                        344
#define TRAINER_GEORGIA                     350
#define TRAINER_KATE_AND_JOY                355
#define TRAINER_VICTOR                      361
#define TRAINER_COLTON                      363
#define TRAINER_VICTORIA                    368
#define TRAINER_VANESSA                     369
#define TRAINER_BETHANY                     370
#define TRAINER_TIMOTHY_1                   376
#define TRAINER_TIMOTHY_2                   377
#define TRAINER_TIMOTHY_3                   378
#define TRAINER_TIMOTHY_4                   379
#define TRAINER_TIMOTHY_5                   380
#define TRAINER_VICKY                       381
#define TRAINER_SHELBY_1                    382
#define TRAINER_SHELBY_2                    383
#define TRAINER_SHELBY_3                    384
#define TRAINER_SHELBY_4                    385
#define TRAINER_SHELBY_5                    386
#define TRAINER_QUINCY                      393
#define TRAINER_KATELYNN                    394
#define TRAINER_JAYLEN                      395
#define TRAINER_DILLON                      396
#define TRAINER_CLAUDE                      406
#define TRAINER_NOLAN                       410
#define TRAINER_BARNY                       411
#define TRAINER_WADE                        412
#define TRAINER_CARTER                      413
#define TRAINER_RONALD                      418
#define TRAINER_JACOB                       419
#define TRAINER_ANTHONY                     420
#define TRAINER_BENJAMIN_1                  421
#define TRAINER_BENJAMIN_2                  422
#define TRAINER_BENJAMIN_3                  423
#define TRAINER_BENJAMIN_4                  424
#define TRAINER_BENJAMIN_5                  425
#define TRAINER_JASMINE                     427
#define TRAINER_ABIGAIL_1                   426
#define TRAINER_ABIGAIL_2                   428
#define TRAINER_ABIGAIL_3                   429
#define TRAINER_ABIGAIL_4                   430
#define TRAINER_ABIGAIL_5                   431
#define TRAINER_CAMDEN                      442
#define TRAINER_DEMETRIUS                   443
#define TRAINER_CHASE                       446
#define TRAINER_ISAIAH_1                    444
#define TRAINER_ISAIAH_2                    447
#define TRAINER_ISAIAH_3                    448
#define TRAINER_ISAIAH_4                    449
#define TRAINER_ISAIAH_5                    450
#define TRAINER_ISOBEL                      451
#define TRAINER_DONNY                       452
#define TRAINER_TALIA                       453
#define TRAINER_ALLISON                     455
#define TRAINER_KATELYN_1                   454
#define TRAINER_KATELYN_2                   456
#define TRAINER_KATELYN_3                   457
#define TRAINER_KATELYN_4                   458
#define TRAINER_KATELYN_5                   459
#define TRAINER_NICOLAS_1                   460
#define TRAINER_NICOLAS_2                   461
#define TRAINER_NICOLAS_3                   462
#define TRAINER_NICOLAS_4                   463
#define TRAINER_NICOLAS_5                   464
#define TRAINER_AARON                       465
#define TRAINER_PERRY                       466
#define TRAINER_HUGH                        467
#define TRAINER_PHIL                        468
#define TRAINER_JARED                       469
#define TRAINER_HUMBERTO                    470
#define TRAINER_PRESLEY                     471
#define TRAINER_EDWARDO                     472
#define TRAINER_COLIN                       473
#define TRAINER_BENNY                       475
#define TRAINER_CHESTER                     476
#define TRAINER_ROBERT_1                    474
#define TRAINER_ROBERT_2                    477
#define TRAINER_ROBERT_3                    478
#define TRAINER_ROBERT_4                    479
#define TRAINER_ROBERT_5                    480
#define TRAINER_ALEX                        481
#define TRAINER_BECK                        482
#define TRAINER_YASU                        483
#define TRAINER_TAKASHI                     484
#define TRAINER_DIANNE                      485
#define TRAINER_JANI                        486
#define TRAINER_LUNG                        488
#define TRAINER_LAO_1                       487
#define TRAINER_LAO_2                       489
#define TRAINER_LAO_3                       490
#define TRAINER_LAO_4                       491
#define TRAINER_LAO_5                       492
#define TRAINER_CORA                        496
#define TRAINER_PAULA                       497
#define TRAINER_CYNDY_1                     495
#define TRAINER_CYNDY_2                     498
#define TRAINER_CYNDY_3                     499
#define TRAINER_CYNDY_4                     500
#define TRAINER_CYNDY_5                     501
#define TRAINER_CLARISSA                    503
#define TRAINER_ANGELICA                    504
#define TRAINER_MADELINE_1                  502
#define TRAINER_MADELINE_2                  505
#define TRAINER_MADELINE_3                  506
#define TRAINER_MADELINE_4                  507
#define TRAINER_MADELINE_5                  508
#define TRAINER_BEVERLY                     509
#define TRAINER_IMANI                       510
#define TRAINER_KYLA                        511
#define TRAINER_DENISE                      512
#define TRAINER_BETH                        513
#define TRAINER_TARA                        514
#define TRAINER_MISSY                       515
#define TRAINER_ALICE                       516
#define TRAINER_GRACE                       518
#define TRAINER_TANYA                       519
#define TRAINER_SHARON                      520
#define TRAINER_NIKKI                       521
#define TRAINER_BRENDA                      522
#define TRAINER_KATIE                       523
#define TRAINER_SUSIE                       524
#define TRAINER_KARA                        525
#define TRAINER_DANA                        526
#define TRAINER_SIENNA                      527
#define TRAINER_DEBRA                       528
#define TRAINER_LINDA                       529
#define TRAINER_KAYLEE                      530
#define TRAINER_LAUREL                      531
#define TRAINER_CARLEE                      532
#define TRAINER_JENNY_1                     517
#define TRAINER_JENNY_2                     533
#define TRAINER_JENNY_3                     534
#define TRAINER_JENNY_4                     535
#define TRAINER_JENNY_5                     536
#define TRAINER_HEIDI                       537
#define TRAINER_BECKY                       538
#define TRAINER_CAROL                       539
#define TRAINER_NANCY                       540
#define TRAINER_MARTHA                      541
#define TRAINER_CEDRIC                      543
#define TRAINER_IRENE                       544
#define TRAINER_DIANA_1                     542
#define TRAINER_DIANA_2                     545
#define TRAINER_DIANA_3                     546
#define TRAINER_DIANA_4                     547
#define TRAINER_DIANA_5                     548
#define TRAINER_MIU_AND_YUKI                552
#define TRAINER_PHILLIP                     560
#define TRAINER_LEONARD                     561
#define TRAINER_DUNCAN                      562
#define TRAINER_ERNEST_1                    558
#define TRAINER_ERNEST_2                    563
#define TRAINER_ERNEST_3                    564
#define TRAINER_ERNEST_4                    565
#define TRAINER_ERNEST_5                    566
#define TRAINER_ELI                         567
#define TRAINER_ANNIKA                      568
#define TRAINER_JAZMYN                      569
#define TRAINER_JONAS                       570
#define TRAINER_KAYLEY                      571
#define TRAINER_AURON                       572
#define TRAINER_KELVIN                      573
#define TRAINER_MARLEY                      574
#define TRAINER_REYNA                       575
#define TRAINER_HUDSON                      576
#define TRAINER_CONOR                       577
#define TRAINER_HECTOR                      579
#define TRAINER_DAVIS                       586
#define TRAINER_MITCHELL                    587
#define TRAINER_HALLE                       593
#define TRAINER_GARRISON                    594
#define TRAINER_LORENZO                     600
#define TRAINER_SEBASTIAN                   601
#define TRAINER_JACKSON_1                   599
#define TRAINER_JACKSON_2                   602
#define TRAINER_JACKSON_3                   603
#define TRAINER_JACKSON_4                   604
#define TRAINER_JACKSON_5                   605
#define TRAINER_JENNA                       607
#define TRAINER_SOPHIA                      608
#define TRAINER_CATHERINE_1                 606
#define TRAINER_CATHERINE_2                 609
#define TRAINER_CATHERINE_3                 610
#define TRAINER_CATHERINE_4                 611
#define TRAINER_CATHERINE_5                 612
#define TRAINER_JULIO                       613
#define TRAINER_SYLVIA                      621
#define TRAINER_LEONARDO                    622
#define TRAINER_ATHENA                      623
#define TRAINER_HARRISON                    624
#define TRAINER_CLARENCE                    626
#define TRAINER_TERRY                       627
#define TRAINER_NATE                        628
#define TRAINER_KATHLEEN                    629
#define TRAINER_CLIFFORD                    630
#define TRAINER_NICHOLAS                    631
#define TRAINER_MACEY                       637
#define TRAINER_PAXTON                      638
#define TRAINER_ISABELLA                    639
#define TRAINER_JONATHAN                    642
#define TRAINER_VIVI                        648
#define TRAINER_ANDREA                      655
#define TRAINER_CRISSY                      656
#define TRAINER_DOUG                        660
#define TRAINER_GREG                        661
#define TRAINER_KENT                        662
#define TRAINER_BRICE                       668
#define TRAINER_LENNY                       670
#define TRAINER_LUCAS                       671
#define TRAINER_ALAN                        672
#define TRAINER_ERIC                        674
#define TRAINER_TRENT_1                     669
#define TRAINER_TRENT_2                     676
#define TRAINER_TRENT_3                     677
#define TRAINER_TRENT_4                     678
#define TRAINER_TRENT_5                     679
#define TRAINER_DEZ_AND_LUKE                680
#define TRAINER_LEA_AND_JED                 681
#define TRAINER_KIRA_AND_DAN_1              682
#define TRAINER_KIRA_AND_DAN_2              683
#define TRAINER_KIRA_AND_DAN_3              684
#define TRAINER_KIRA_AND_DAN_4              685
#define TRAINER_KIRA_AND_DAN_5              686
#define TRAINER_GERALD                      688
#define TRAINER_DANIELLE                    690
#define TRAINER_HIDEO                       691
#define TRAINER_KEIGO                       692
#define TRAINER_RILEY                       693
#define TRAINER_FLINT                       694
#define TRAINER_ASHLEY                      695
#define TRAINER_JONAH                       696
#define TRAINER_HENRY                       697
#define TRAINER_ROGER                       698
#define TRAINER_ALEXA                       699
#define TRAINER_RUBEN                       700
#define TRAINER_WAYNE                       702
#define TRAINER_AIDAN                       703
#define TRAINER_REED                        704
#define TRAINER_TISHA                       705
#define TRAINER_TORI_AND_TIA                706
#define TRAINER_KIM_AND_IRIS                707
#define TRAINER_TYRA_AND_IVY                708
#define TRAINER_MEL_AND_PAUL                709
#define TRAINER_JOHN_AND_JAY_1              710
#define TRAINER_JOHN_AND_JAY_2              711
#define TRAINER_JOHN_AND_JAY_3              712
#define TRAINER_JOHN_AND_JAY_4              713
#define TRAINER_JOHN_AND_JAY_5              714
#define TRAINER_RELI_AND_IAN                715
#define TRAINER_LILA_AND_ROY_1              716
#define TRAINER_LILA_AND_ROY_2              717
#define TRAINER_LILA_AND_ROY_3              718
#define TRAINER_LILA_AND_ROY_4              719
#define TRAINER_LILA_AND_ROY_5              720
#define TRAINER_LISA_AND_RAY                721
#define TRAINER_CHRIS                       722
#define TRAINER_TYRON                       733
#define TRAINER_LILY                        734
#define TRAINER_BIANCA                      735
#define TRAINER_HAYDEN                      736
#define TRAINER_SOPHIE                      737
#define TRAINER_COBY                        738
#define TRAINER_LAWRENCE                    739
#define TRAINER_WYATT                       740
#define TRAINER_ANGELINA                    741
#define TRAINER_KAI                         742
#define TRAINER_CHARLOTTE                   743
#define TRAINER_DEANDRE                     744
#define TRAINER_DARCY                       762
#define TRAINER_PETE                        764
#define TRAINER_ISABELLE                    765
#define TRAINER_JOSUE                       767
#define TRAINER_CAMRON                      768
#define TRAINER_CAROLINA                    770
#define TRAINER_ELIJAH                      771
#define TRAINER_CELIA                       772
#define TRAINER_BRYAN                       773
#define TRAINER_BRANDEN                     774
#define TRAINER_BRYANT                      775
#define TRAINER_SHAYLA                      776
#define TRAINER_KYRA                        777
#define TRAINER_JAIDEN                      778
#define TRAINER_ALIX                        779
#define TRAINER_HELENE                      780
#define TRAINER_MARLENE                     781
#define TRAINER_MAKAYLA                     787
#define TRAINER_FABIAN                      788
#define TRAINER_DAYTON                      789
#define TRAINER_RACHEL                      790
#define TRAINER_LEONEL                      791
#define TRAINER_CALLIE                      792
#define TRAINER_CALE                        793
#define TRAINER_MYLES                       794
#define TRAINER_PAT                         795
#define TRAINER_DARIUS                      798
#define TRAINER_ANABEL                      799
#define TRAINER_TUCKER                      800
#define TRAINER_SPENSER                     801
#define TRAINER_GRETA                       802
#define TRAINER_NOLAND                      803
#define TRAINER_LUCY                        804
#define TRAINER_BRANDON                     805
#define TRAINER_ANDRES_1                    766
#define TRAINER_ANDRES_2                    806
#define TRAINER_ANDRES_3                    807
#define TRAINER_ANDRES_4                    808
#define TRAINER_ANDRES_5                    809
#define TRAINER_CORY_1                      769
#define TRAINER_CORY_2                      810
#define TRAINER_CORY_3                      811
#define TRAINER_CORY_4                      812
#define TRAINER_CORY_5                      813
#define TRAINER_PABLO_1                     445
#define TRAINER_PABLO_2                     814
#define TRAINER_PABLO_3                     815
#define TRAINER_PABLO_4                     816
#define TRAINER_PABLO_5                     817
#define TRAINER_KOJI_1                      701
#define TRAINER_KOJI_2                      818
#define TRAINER_KOJI_3                      819
#define TRAINER_KOJI_4                      820
#define TRAINER_KOJI_5                      821
#define TRAINER_CRISTIN_1                   796
#define TRAINER_CRISTIN_2                   822
#define TRAINER_CRISTIN_3                   823
#define TRAINER_CRISTIN_4                   824
#define TRAINER_CRISTIN_5                   825
#define TRAINER_FERNANDO_1                  276
#define TRAINER_FERNANDO_2                  826
#define TRAINER_FERNANDO_3                  827
#define TRAINER_FERNANDO_4                  828
#define TRAINER_FERNANDO_5                  829
#define TRAINER_THALIA_1                    225
#define TRAINER_THALIA_2                    838
#define TRAINER_THALIA_3                    839
#define TRAINER_THALIA_4                    840
#define TRAINER_THALIA_5                    841
#define TRAINER_MARIELA                     842
#define TRAINER_ALVARO                      843
#define TRAINER_EVERETT                     844
#define TRAINER_GRUNT_MT_CHIMNEY_1          227
#define TRAINER_GRUNT_MT_CHIMNEY_2          625
#define TRAINER_TABITHA_MT_CHIMNEY          641
#define TRAINER_MAXIE_MT_CHIMNEY            644
#define TRAINER_GRUNT_JAGGED_PASS           616
#define TRAINER_GRUNT_WEATHER_INST_1        105
#define TRAINER_GRUNT_WEATHER_INST_2        106
#define TRAINER_GRUNT_WEATHER_INST_3        107
#define TRAINER_GRUNT_WEATHER_INST_4        114
#define TRAINER_GRUNT_WEATHER_INST_5        640
#define TRAINER_SHELLY_WEATHER_INSTITUTE    120
#define TRAINER_GRUNT_MT_PYRE_1             111
#define TRAINER_GRUNT_MT_PYRE_2             112
#define TRAINER_GRUNT_MT_PYRE_3             113
#define TRAINER_GRUNT_MT_PYRE_4             615
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1       745
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2       746
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3       747
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4       748
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5       749
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6       750
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7       751
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8       752
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9       753
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10      754
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11      755
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12      756
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13      757
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14      758
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15      759
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16      760
#define TRAINER_TABITHA_MAGMA_HIDEOUT       761
#define TRAINER_MAXIE_MAGMA_HIDEOUT         643
#define TRAINER_GRUNT_AQUA_HIDEOUT_1         90
#define TRAINER_GRUNT_AQUA_HIDEOUT_2         91
#define TRAINER_GRUNT_AQUA_HIDEOUT_3         92
#define TRAINER_GRUNT_AQUA_HIDEOUT_4         93
#define TRAINER_GRUNT_AQUA_HIDEOUT_5        115
#define TRAINER_GRUNT_AQUA_HIDEOUT_6        116
#define TRAINER_GRUNT_AQUA_HIDEOUT_7        273
#define TRAINER_GRUNT_AQUA_HIDEOUT_8        274
#define TRAINER_MATT_AQUA_HIDEOUT           118
#define TRAINER_GRUNT_SPACE_CENTER_1        110
#define TRAINER_GRUNT_SPACE_CENTER_2        632
#define TRAINER_GRUNT_SPACE_CENTER_3        633
#define TRAINER_GRUNT_SPACE_CENTER_4        634
#define TRAINER_GRUNT_SPACE_CENTER_5        635
#define TRAINER_GRUNT_SPACE_CENTER_6        636
#define TRAINER_COURTNEY_SPACE_CENTER       198
#define TRAINER_TABITHA_SPACE_CENTER        580
#define TRAINER_MAXIE_SPACE_CENTER          763
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_1      94
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_2      95
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_3      96
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_4     102
#define TRAINER_MATT_SEAFLOOR_CAVERN        614
#define TRAINER_SHELLY_SEAFLOOR_CAVERN      121
#define TRAINER_RED                         845
#define TRAINER_LEAF                        846
#define TRAINER_BRENDAN_PLACEHOLDER         847
#define TRAINER_MAY_PLACEHOLDER             848
#define TRAINER_UNUSED_1                    849
#define TRAINER_UNUSED_2                    850
#define TRAINER_UNUSED_3                    851
#define TRAINER_UNUSED_4                    852
#define TRAINER_UNUSED_5                    853

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT                      855
#define MAX_TRAINERS_COUNT                  864
#define TRAINER_PARTNER(partner)           (MAX_TRAINERS_COUNT + partner)

#endif  // GUARD_CONSTANTS_OPPONENTS_H
