#ifndef GUARD_CONSTANTS_OPPONENTS_FRLG_H
#define GUARD_CONSTANTS_OPPONENTS_FRLG_H

#include "constants/battle_partner.h"

#define TRAINER_NONE                                0
// Important trainers
#define TRAINER_RIVAL_OAKS_LAB_GRASS                1
#define TRAINER_RIVAL_OAKS_LAB_FIRE                 2
#define TRAINER_RIVAL_OAKS_LAB_WATER                3
#define TRAINER_RIVAL_ROUTE_22_EARLY_GRASS          4
#define TRAINER_RIVAL_ROUTE_22_EARLY_FIRE           5
#define TRAINER_RIVAL_ROUTE_22_EARLY_WATER          6
#define TRAINER_RIVAL_CERULEAN_GRASS                7
#define TRAINER_RIVAL_CERULEAN_FIRE                 8
#define TRAINER_RIVAL_CERULEAN_WATER                9
#define TRAINER_RIVAL_SS_ANNE_GRASS                10
#define TRAINER_RIVAL_SS_ANNE_FIRE                 11
#define TRAINER_RIVAL_SS_ANNE_WATER                12
#define TRAINER_RIVAL_POKEMON_TOWER_GRASS          13
#define TRAINER_RIVAL_POKEMON_TOWER_FIRE           14
#define TRAINER_RIVAL_POKEMON_TOWER_WATER          15
#define TRAINER_RIVAL_SILPH_GRASS                  16
#define TRAINER_RIVAL_SILPH_FIRE                   17
#define TRAINER_RIVAL_SILPH_WATER                  18
#define TRAINER_RIVAL_ROUTE_22_LATE_GRASS          19
#define TRAINER_RIVAL_ROUTE_22_LATE_FIRE           20
#define TRAINER_RIVAL_ROUTE_22_LATE_WATER          21
#define TRAINER_CHAMPION_FIRST_GRASS               22
#define TRAINER_CHAMPION_FIRST_FIRE                23
#define TRAINER_CHAMPION_FIRST_WATER               24
#define TRAINER_CHAMPION_REMATCH_GRASS             25
#define TRAINER_CHAMPION_REMATCH_FIRE              26
#define TRAINER_CHAMPION_REMATCH_WATER             27
#define TRAINER_LEADER_BROCK                       28
#define TRAINER_LEADER_BROCK_2                     29
#define TRAINER_LEADER_MISTY                       30
#define TRAINER_LEADER_MISTY_2                     31
#define TRAINER_LEADER_LT_SURGE                    32
#define TRAINER_LEADER_LT_SURGE_2                  33
#define TRAINER_LEADER_ERIKA                       34
#define TRAINER_LEADER_ERIKA_2                     35
#define TRAINER_LEADER_KOGA                        36
#define TRAINER_LEADER_KOGA_2                      37
#define TRAINER_LEADER_SABRINA                     38
#define TRAINER_LEADER_SABRINA_2                   39
#define TRAINER_LEADER_BLAINE                      40
#define TRAINER_LEADER_BLAINE_2                    41
#define TRAINER_BOSS_GIOVANNI                      42
#define TRAINER_BOSS_GIOVANNI_2                    43
#define TRAINER_LEADER_GIOVANNI                    44
#define TRAINER_LEADER_GIOVANNI_2                  45
#define TRAINER_ELITE_FOUR_LORELEI                 46
#define TRAINER_ELITE_FOUR_LORELEI_2               47
#define TRAINER_ELITE_FOUR_BRUNO                   48
#define TRAINER_ELITE_FOUR_BRUNO_2                 49
#define TRAINER_ELITE_FOUR_AGATHA                  50
#define TRAINER_ELITE_FOUR_AGATHA_2                51
#define TRAINER_ELITE_FOUR_LANCE                   52
#define TRAINER_ELITE_FOUR_LANCE_2                 53
// Regular trainers
#define TRAINER_YOUNGSTER_BEN                      54
#define TRAINER_YOUNGSTER_CALVIN                   55
#define TRAINER_YOUNGSTER_JOSH                     56
#define TRAINER_YOUNGSTER_TIMMY                    57
#define TRAINER_YOUNGSTER_JOEY                     58
#define TRAINER_YOUNGSTER_DAN                      59
#define TRAINER_YOUNGSTER_CHAD                     60
#define TRAINER_YOUNGSTER_TYLER                    61
#define TRAINER_YOUNGSTER_EDDIE                    62
#define TRAINER_YOUNGSTER_DILLON                   63
#define TRAINER_YOUNGSTER_YASU                     64
#define TRAINER_YOUNGSTER_DAVE                     65
#define TRAINER_YOUNGSTER_BEN_2                    66
#define TRAINER_BUG_CATCHER_RICK                   67
#define TRAINER_BUG_CATCHER_DOUG                   68
#define TRAINER_BUG_CATCHER_SAMMY                  69
#define TRAINER_BUG_CATCHER_COLTON                 70
#define TRAINER_BUG_CATCHER_GREG                   71
#define TRAINER_BUG_CATCHER_JAMES                  72
#define TRAINER_BUG_CATCHER_KENT                   73
#define TRAINER_BUG_CATCHER_ROBBY                  74
#define TRAINER_BUG_CATCHER_CALE                   75
#define TRAINER_BUG_CATCHER_KEIGO                  76
#define TRAINER_BUG_CATCHER_ELIJAH                 77
#define TRAINER_BUG_CATCHER_BRENT                  78
#define TRAINER_BUG_CATCHER_CONNER                 79
#define TRAINER_LASS_JANICE                        80
#define TRAINER_LASS_SALLY                         81
#define TRAINER_LASS_ROBIN                         82
#define TRAINER_LASS_CRISSY                        83
#define TRAINER_LASS_MIRIAM                        84
#define TRAINER_LASS_IRIS                          85
#define TRAINER_LASS_RELI                          86
#define TRAINER_LASS_ALI                           87
#define TRAINER_LASS_HALEY                         88
#define TRAINER_LASS_ANN                           89
#define TRAINER_LASS_DAWN                          90
#define TRAINER_LASS_PAIGE                         91
#define TRAINER_LASS_ANDREA                        92
#define TRAINER_LASS_MEGAN                         93
#define TRAINER_LASS_JULIA                         94
#define TRAINER_LASS_KAY                           95
#define TRAINER_LASS_LISA                          96
#define TRAINER_SAILOR_EDMOND                      97
#define TRAINER_SAILOR_TREVOR                      98
#define TRAINER_SAILOR_LEONARD                     99
#define TRAINER_SAILOR_DUNCAN                     100
#define TRAINER_SAILOR_HUEY                       101
#define TRAINER_SAILOR_DYLAN                      102
#define TRAINER_SAILOR_PHILLIP                    103
#define TRAINER_SAILOR_DWAYNE                     104
#define TRAINER_CAMPER_LIAM                       105
#define TRAINER_CAMPER_SHANE                      106
#define TRAINER_CAMPER_ETHAN                      107
#define TRAINER_CAMPER_RICKY                      108
#define TRAINER_CAMPER_JEFF                       109
#define TRAINER_CAMPER_CHRIS                      110
#define TRAINER_CAMPER_DREW                       111
#define TRAINER_PICNICKER_DIANA                   112
#define TRAINER_PICNICKER_NANCY                   113
#define TRAINER_PICNICKER_ISABELLE                114
#define TRAINER_PICNICKER_KELSEY                  115
#define TRAINER_PICNICKER_ALICIA                  116
#define TRAINER_PICNICKER_CAITLIN                 117
#define TRAINER_PICNICKER_HEIDI                   118
#define TRAINER_PICNICKER_CAROL                   119
#define TRAINER_PICNICKER_SOFIA                   120
#define TRAINER_PICNICKER_MARTHA                  121
#define TRAINER_PICNICKER_TINA                    122
#define TRAINER_PICNICKER_HANNAH                  123
#define TRAINER_POKEMANIAC_MARK                   124
#define TRAINER_POKEMANIAC_HERMAN                 125
#define TRAINER_POKEMANIAC_COOPER                 126
#define TRAINER_POKEMANIAC_STEVE                  127
#define TRAINER_POKEMANIAC_WINSTON                128
#define TRAINER_POKEMANIAC_DAWSON                 129
#define TRAINER_POKEMANIAC_ASHTON                 130
#define TRAINER_SUPER_NERD_JOVAN                  131
#define TRAINER_SUPER_NERD_MIGUEL                 132
#define TRAINER_SUPER_NERD_AIDAN                  133
#define TRAINER_SUPER_NERD_GLENN                  134
#define TRAINER_SUPER_NERD_LESLIE                 135
#define TRAINER_SUPER_NERD_ERIK                   136
#define TRAINER_SUPER_NERD_AVERY                  137
#define TRAINER_SUPER_NERD_DEREK                  138
#define TRAINER_SUPER_NERD_ZAC                    139
#define TRAINER_HIKER_MARCOS                      140
#define TRAINER_HIKER_FRANKLIN                    141
#define TRAINER_HIKER_NOB                         142
#define TRAINER_HIKER_WAYNE                       143
#define TRAINER_HIKER_ALAN                        144
#define TRAINER_HIKER_BRICE                       145
#define TRAINER_HIKER_CLARK                       146
#define TRAINER_HIKER_TRENT                       147
#define TRAINER_HIKER_DUDLEY                      148
#define TRAINER_HIKER_ALLEN                       149
#define TRAINER_HIKER_ERIC                        150
#define TRAINER_HIKER_LENNY                       151
#define TRAINER_HIKER_OLIVER                      152
#define TRAINER_HIKER_LUCAS                        153
#define TRAINER_BIKER_JARED                        154
#define TRAINER_BIKER_MALIK                        155
#define TRAINER_BIKER_ERNEST                       156
#define TRAINER_BIKER_ALEX                         157
#define TRAINER_BIKER_LAO                          158
#define TRAINER_BIKER_HIDEO                        159
#define TRAINER_BIKER_RUBEN                        160
#define TRAINER_BIKER_BILLY                        161
#define TRAINER_BIKER_NIKOLAS                      162
#define TRAINER_BIKER_JAXON                        163
#define TRAINER_BIKER_WILLIAM                      164
#define TRAINER_BIKER_LUKAS                        165
#define TRAINER_BIKER_ISAAC                        166
#define TRAINER_BIKER_GERALD                       167
#define TRAINER_BURGLAR_QUINN                      168
#define TRAINER_BURGLAR_RAMON                      169
#define TRAINER_BURGLAR_DUSTY                      170
#define TRAINER_BURGLAR_ARNIE                      171
#define TRAINER_BURGLAR_SIMON                      172
#define TRAINER_BURGLAR_LEWIS                      173
#define TRAINER_ENGINEER_BAILY                     174
#define TRAINER_ENGINEER_BRAXTON                   175
#define TRAINER_ENGINEER_BERNIE                    176
#define TRAINER_FISHERMAN_DALE                     177
#define TRAINER_FISHERMAN_BARNY                    178
#define TRAINER_FISHERMAN_NED                      179
#define TRAINER_FISHERMAN_CHIP                     180
#define TRAINER_FISHERMAN_HANK                     181
#define TRAINER_FISHERMAN_ELLIOT                   182
#define TRAINER_FISHERMAN_RONALD                   183
#define TRAINER_FISHERMAN_CLAUDE                   184
#define TRAINER_FISHERMAN_WADE                     185
#define TRAINER_FISHERMAN_NOLAN                    186
#define TRAINER_FISHERMAN_ANDREW                   187
#define TRAINER_SWIMMER_MALE_LUIS                  188
#define TRAINER_SWIMMER_MALE_RICHARD               189
#define TRAINER_SWIMMER_MALE_REECE                 190
#define TRAINER_SWIMMER_MALE_MATTHEW               191
#define TRAINER_SWIMMER_MALE_DOUGLAS               192
#define TRAINER_SWIMMER_MALE_DAVID                 193
#define TRAINER_SWIMMER_MALE_TONY                  194
#define TRAINER_SWIMMER_MALE_AXLE                  195
#define TRAINER_SWIMMER_MALE_BARRY                 196
#define TRAINER_SWIMMER_MALE_DEAN                  197
#define TRAINER_SWIMMER_MALE_DARRIN                198
#define TRAINER_SWIMMER_MALE_SPENCER               199
#define TRAINER_SWIMMER_MALE_JACK                  200
#define TRAINER_SWIMMER_MALE_JEROME                201
#define TRAINER_SWIMMER_MALE_ROLAND                202
#define TRAINER_CUE_BALL_KOJI                      203
#define TRAINER_CUE_BALL_LUKE                      204
#define TRAINER_CUE_BALL_CAMRON                    205
#define TRAINER_CUE_BALL_RAUL                      206
#define TRAINER_CUE_BALL_ISAIAH                    207
#define TRAINER_CUE_BALL_ZEEK                      208
#define TRAINER_CUE_BALL_JAMAL                     209
#define TRAINER_CUE_BALL_COREY                     210
#define TRAINER_CUE_BALL_CHASE                     211
#define TRAINER_GAMER_HUGO                         212
#define TRAINER_GAMER_JASPER                       213
#define TRAINER_GAMER_DIRK                         214
#define TRAINER_GAMER_DARIAN                       215
#define TRAINER_GAMER_STAN                         216
#define TRAINER_GAMER_RICH                         217
#define TRAINER_BEAUTY_BRIDGET                     218
#define TRAINER_BEAUTY_TAMIA                       219
#define TRAINER_BEAUTY_LORI                        220
#define TRAINER_BEAUTY_LOLA                        221
#define TRAINER_BEAUTY_SHEILA                      222
#define TRAINER_SWIMMER_FEMALE_TIFFANY             223
#define TRAINER_SWIMMER_FEMALE_NORA                224
#define TRAINER_SWIMMER_FEMALE_MELISSA             225
#define TRAINER_BEAUTY_GRACE                       226
#define TRAINER_BEAUTY_OLIVIA                      227
#define TRAINER_BEAUTY_LAUREN                      228
#define TRAINER_SWIMMER_FEMALE_ANYA                229
#define TRAINER_SWIMMER_FEMALE_ALICE               230
#define TRAINER_SWIMMER_FEMALE_CONNIE              231
#define TRAINER_SWIMMER_FEMALE_SHIRLEY             232
#define TRAINER_PSYCHIC_JOHAN                      233
#define TRAINER_PSYCHIC_TYRON                      234
#define TRAINER_PSYCHIC_CAMERON                    235
#define TRAINER_PSYCHIC_PRESTON                    236
#define TRAINER_ROCKER_RANDALL                     237
#define TRAINER_ROCKER_LUCA                        238
#define TRAINER_JUGGLER_DALTON                     239
#define TRAINER_JUGGLER_NELSON                     240
#define TRAINER_JUGGLER_KIRK                       241
#define TRAINER_JUGGLER_SHAWN                      242
#define TRAINER_JUGGLER_GREGORY                    243
#define TRAINER_JUGGLER_EDWARD                     244
#define TRAINER_JUGGLER_KAYDEN                     245
#define TRAINER_JUGGLER_NATE                       246
#define TRAINER_TAMER_PHIL                         247
#define TRAINER_TAMER_EDGAR                        248
#define TRAINER_TAMER_JASON                        249
#define TRAINER_TAMER_COLE                         250
#define TRAINER_TAMER_VINCENT                      251
#define TRAINER_TAMER_JOHN                         252
#define TRAINER_BIRD_KEEPER_SEBASTIAN              253
#define TRAINER_BIRD_KEEPER_PERRY                  254
#define TRAINER_BIRD_KEEPER_ROBERT                 255
#define TRAINER_BIRD_KEEPER_DONALD                 256
#define TRAINER_BIRD_KEEPER_BENNY                  257
#define TRAINER_BIRD_KEEPER_EDWIN                  258
#define TRAINER_BIRD_KEEPER_CHESTER                259
#define TRAINER_BIRD_KEEPER_WILTON                 260
#define TRAINER_BIRD_KEEPER_RAMIRO                 261
#define TRAINER_BIRD_KEEPER_JACOB                  262
#define TRAINER_BIRD_KEEPER_ROGER                  263
#define TRAINER_BIRD_KEEPER_REED                   264
#define TRAINER_BIRD_KEEPER_KEITH                  265
#define TRAINER_BIRD_KEEPER_CARTER                 266
#define TRAINER_BIRD_KEEPER_MITCH                  267
#define TRAINER_BIRD_KEEPER_BECK                   268
#define TRAINER_BIRD_KEEPER_MARLON                 269
#define TRAINER_BLACK_BELT_KOICHI                  270
#define TRAINER_BLACK_BELT_MIKE                    271
#define TRAINER_BLACK_BELT_HIDEKI                  272
#define TRAINER_BLACK_BELT_AARON                   273
#define TRAINER_BLACK_BELT_HITOSHI                 274
#define TRAINER_BLACK_BELT_ATSUSHI                 275
#define TRAINER_BLACK_BELT_KIYO                    276
#define TRAINER_BLACK_BELT_TAKASHI                 277
#define TRAINER_BLACK_BELT_DAISUKE                 278
#define TRAINER_SCIENTIST_TED                      279
#define TRAINER_SCIENTIST_CONNOR                   280
#define TRAINER_SCIENTIST_JERRY                    281
#define TRAINER_SCIENTIST_JOSE                     282
#define TRAINER_SCIENTIST_RODNEY                   283
#define TRAINER_SCIENTIST_BEAU                     284
#define TRAINER_SCIENTIST_TAYLOR                   285
#define TRAINER_SCIENTIST_JOSHUA                   286
#define TRAINER_SCIENTIST_PARKER                   287
#define TRAINER_SCIENTIST_ED                       288
#define TRAINER_SCIENTIST_TRAVIS                   289
#define TRAINER_SCIENTIST_BRAYDON                  290
#define TRAINER_SCIENTIST_IVAN                     291
#define TRAINER_TEAM_ROCKET_GRUNT                  292
#define TRAINER_TEAM_ROCKET_GRUNT_2                293
#define TRAINER_TEAM_ROCKET_GRUNT_3                294
#define TRAINER_TEAM_ROCKET_GRUNT_4                295
#define TRAINER_TEAM_ROCKET_GRUNT_5                296
#define TRAINER_TEAM_ROCKET_GRUNT_6                297
#define TRAINER_TEAM_ROCKET_GRUNT_7                298
#define TRAINER_TEAM_ROCKET_GRUNT_8                299
#define TRAINER_TEAM_ROCKET_GRUNT_9                300
#define TRAINER_TEAM_ROCKET_GRUNT_10               301
#define TRAINER_TEAM_ROCKET_GRUNT_11               302
#define TRAINER_TEAM_ROCKET_GRUNT_12               303
#define TRAINER_TEAM_ROCKET_GRUNT_13               304
#define TRAINER_TEAM_ROCKET_GRUNT_14               305
#define TRAINER_TEAM_ROCKET_GRUNT_15               306
#define TRAINER_TEAM_ROCKET_GRUNT_16               307
#define TRAINER_TEAM_ROCKET_GRUNT_17               308
#define TRAINER_TEAM_ROCKET_GRUNT_18               309
#define TRAINER_TEAM_ROCKET_GRUNT_19               310
#define TRAINER_TEAM_ROCKET_GRUNT_20               311
#define TRAINER_TEAM_ROCKET_GRUNT_21               312
#define TRAINER_TEAM_ROCKET_GRUNT_22               313
#define TRAINER_TEAM_ROCKET_GRUNT_23               314
#define TRAINER_TEAM_ROCKET_GRUNT_24               315
#define TRAINER_TEAM_ROCKET_GRUNT_25               316
#define TRAINER_TEAM_ROCKET_GRUNT_26               317
#define TRAINER_TEAM_ROCKET_GRUNT_27               318
#define TRAINER_TEAM_ROCKET_GRUNT_28               319
#define TRAINER_TEAM_ROCKET_GRUNT_29               320
#define TRAINER_TEAM_ROCKET_GRUNT_30               321
#define TRAINER_TEAM_ROCKET_GRUNT_31               322
#define TRAINER_TEAM_ROCKET_GRUNT_32               323
#define TRAINER_TEAM_ROCKET_GRUNT_33               324
#define TRAINER_TEAM_ROCKET_GRUNT_34               325
#define TRAINER_TEAM_ROCKET_GRUNT_35               326
#define TRAINER_TEAM_ROCKET_GRUNT_36               327
#define TRAINER_TEAM_ROCKET_GRUNT_37               328
#define TRAINER_TEAM_ROCKET_GRUNT_38               329
#define TRAINER_TEAM_ROCKET_GRUNT_39               330
#define TRAINER_TEAM_ROCKET_GRUNT_40               331
#define TRAINER_TEAM_ROCKET_GRUNT_41               332
#define TRAINER_COOLTRAINER_SAMUEL                 333
#define TRAINER_COOLTRAINER_GEORGE                 334
#define TRAINER_COOLTRAINER_COLBY                  335
#define TRAINER_COOLTRAINER_PAUL                   336
#define TRAINER_COOLTRAINER_ROLANDO                337
#define TRAINER_COOLTRAINER_GILBERT                338
#define TRAINER_COOLTRAINER_OWEN                   339
#define TRAINER_COOLTRAINER_BERKE                  340
#define TRAINER_COOLTRAINER_YUJI                   341
#define TRAINER_COOLTRAINER_WARREN                 342
#define TRAINER_COOLTRAINER_MARY                   343
#define TRAINER_COOLTRAINER_CAROLINE               344
#define TRAINER_COOLTRAINER_ALEXA                  345
#define TRAINER_COOLTRAINER_SHANNON                346
#define TRAINER_COOLTRAINER_NAOMI                  347
#define TRAINER_COOLTRAINER_BROOKE                 348
#define TRAINER_COOLTRAINER_AUSTINA                349
#define TRAINER_COOLTRAINER_JULIE                  350
#define TRAINER_GENTLEMAN_THOMAS                   351
#define TRAINER_GENTLEMAN_ARTHUR                   352
#define TRAINER_GENTLEMAN_TUCKER                   353
#define TRAINER_GENTLEMAN_NORTON                   354
#define TRAINER_GENTLEMAN_WALTER                   355
#define TRAINER_CHANNELER_PATRICIA                 356
#define TRAINER_CHANNELER_CARLY                    357
#define TRAINER_CHANNELER_HOPE                     358
#define TRAINER_CHANNELER_PAULA                    359
#define TRAINER_CHANNELER_LAUREL                   360
#define TRAINER_CHANNELER_JODY                     361
#define TRAINER_CHANNELER_TAMMY                    362
#define TRAINER_CHANNELER_RUTH                     363
#define TRAINER_CHANNELER_KARINA                   364
#define TRAINER_CHANNELER_JANAE                    365
#define TRAINER_CHANNELER_ANGELICA                 366
#define TRAINER_CHANNELER_EMILIA                   367
#define TRAINER_CHANNELER_JENNIFER                 368
#define TRAINER_CHANNELER_AMANDA                   369
#define TRAINER_CHANNELER_STACY                    370
#define TRAINER_CHANNELER_TASHA                    371
#define TRAINER_HIKER_JEREMY                       372
#define TRAINER_PICNICKER_ALMA                     373
#define TRAINER_PICNICKER_SUSIE                    374
#define TRAINER_PICNICKER_VALERIE                  375
#define TRAINER_PICNICKER_GWEN                     376
#define TRAINER_BIKER_VIRGIL                       377
#define TRAINER_CAMPER_FLINT                       378
#define TRAINER_PICNICKER_MISSY                    379
#define TRAINER_PICNICKER_IRENE                    380
#define TRAINER_PICNICKER_DANA                     381
#define TRAINER_PICNICKER_ARIANA                   382
#define TRAINER_PICNICKER_LEAH                     383
#define TRAINER_CAMPER_JUSTIN                      384
#define TRAINER_PICNICKER_YAZMIN                   385
#define TRAINER_PICNICKER_KINDRA                   386
#define TRAINER_PICNICKER_BECKY                    387
#define TRAINER_PICNICKER_CELIA                    388
#define TRAINER_GENTLEMAN_BROOKS                   389
#define TRAINER_GENTLEMAN_LAMAR                    390
#define TRAINER_TWINS_ELI_ANNE                     391
#define TRAINER_COOL_COUPLE_RAY_TYRA               392
#define TRAINER_YOUNG_COUPLE_GIA_JES               393
#define TRAINER_TWINS_KIRI_JAN                     394
#define TRAINER_CRUSH_KIN_RON_MYA                  395
#define TRAINER_YOUNG_COUPLE_LEA_JED               396
#define TRAINER_SIS_AND_BRO_LIA_LUC                397
#define TRAINER_SIS_AND_BRO_LIL_IAN                398
#define TRAINER_YOUNGSTER_BEN_3                    399
#define TRAINER_YOUNGSTER_BEN_4                    400
#define TRAINER_YOUNGSTER_CHAD_2                   401
#define TRAINER_LASS_RELI_2                        402
#define TRAINER_LASS_RELI_3                        403
#define TRAINER_YOUNGSTER_TIMMY_2                  404
#define TRAINER_YOUNGSTER_TIMMY_3                  405
#define TRAINER_YOUNGSTER_TIMMY_4                  406
#define TRAINER_YOUNGSTER_CHAD_3                   407
#define TRAINER_LASS_JANICE_2                      408
#define TRAINER_LASS_JANICE_3                      409
#define TRAINER_YOUNGSTER_CHAD_4                   410
#define TRAINER_HIKER_FRANKLIN_2                   411
#define TRAINER_PKMN_PROF_PROF_OAK                 412
#define TRAINER_TEAM_ROCKET_GRUNT_42               413
#define TRAINER_PSYCHIC_JACLYN                     414
#define TRAINER_CRUSH_GIRL_SHARON                  415
#define TRAINER_TUBER_AMIRA                        416
#define TRAINER_PKMN_BREEDER_ALIZE                 417
#define TRAINER_PKMN_RANGER_NICOLAS                418
#define TRAINER_PKMN_RANGER_MADELINE               419
#define TRAINER_AROMA_LADY_NIKKI                   420
#define TRAINER_RUIN_MANIAC_STANLY                 421
#define TRAINER_LADY_JACKI                         422
#define TRAINER_PAINTER_DAISY                      423
#define TRAINER_BIKER_GOON                         424
#define TRAINER_BIKER_GOON_2                       425
#define TRAINER_BIKER_GOON_3                       426
#define TRAINER_BUG_CATCHER_ANTHONY                427
#define TRAINER_BUG_CATCHER_CHARLIE                428
#define TRAINER_TWINS_ELI_ANNE_2                   429
#define TRAINER_YOUNGSTER_JOHNSON                  430
#define TRAINER_BIKER_RICARDO                      431
#define TRAINER_BIKER_JAREN                        432
#define TRAINER_TEAM_ROCKET_GRUNT_43               433
#define TRAINER_TEAM_ROCKET_GRUNT_44               434
#define TRAINER_TEAM_ROCKET_GRUNT_45               435
#define TRAINER_TEAM_ROCKET_GRUNT_46               436
#define TRAINER_TEAM_ROCKET_GRUNT_47               437
#define TRAINER_TEAM_ROCKET_GRUNT_48               438
#define TRAINER_TEAM_ROCKET_ADMIN                  439
#define TRAINER_TEAM_ROCKET_ADMIN_2                440
#define TRAINER_SCIENTIST_GIDEON                   441
#define TRAINER_SWIMMER_FEMALE_AMARA               442
#define TRAINER_SWIMMER_FEMALE_MARIA               443
#define TRAINER_SWIMMER_FEMALE_ABIGAIL             444
#define TRAINER_SWIMMER_MALE_FINN                  445
#define TRAINER_SWIMMER_MALE_GARRETT               446
#define TRAINER_FISHERMAN_TOMMY                    447
#define TRAINER_CRUSH_GIRL_TANYA                   448
#define TRAINER_BLACK_BELT_SHEA                    449
#define TRAINER_BLACK_BELT_HUGH                    450
#define TRAINER_CAMPER_BRYCE                       451
#define TRAINER_PICNICKER_CLAIRE                   452
#define TRAINER_CRUSH_KIN_MIK_KIA                  453
#define TRAINER_AROMA_LADY_VIOLET                  454
#define TRAINER_TUBER_ALEXIS                       455
#define TRAINER_TWINS_JOY_MEG                      456
#define TRAINER_SWIMMER_FEMALE_TISHA               457
#define TRAINER_PAINTER_CELINA                     458
#define TRAINER_PAINTER_RAYNA                      459
#define TRAINER_LADY_GILLIAN                       460
#define TRAINER_YOUNGSTER_DESTIN                   461
#define TRAINER_SWIMMER_MALE_TOBY                  462
#define TRAINER_TEAM_ROCKET_GRUNT_49               463
#define TRAINER_TEAM_ROCKET_GRUNT_50               464
#define TRAINER_TEAM_ROCKET_GRUNT_51               465
#define TRAINER_BIRD_KEEPER_MILO                   466
#define TRAINER_BIRD_KEEPER_CHAZ                   467
#define TRAINER_BIRD_KEEPER_HAROLD                 468
#define TRAINER_FISHERMAN_TYLOR                    469
#define TRAINER_SWIMMER_MALE_MYMO                  470
#define TRAINER_SWIMMER_FEMALE_NICOLE              471
#define TRAINER_SIS_AND_BRO_AVA_GEB                472
#define TRAINER_AROMA_LADY_ROSE                    473
#define TRAINER_SWIMMER_MALE_SAMIR                 474
#define TRAINER_SWIMMER_FEMALE_DENISE              475
#define TRAINER_TWINS_MIU_MIA                      476
#define TRAINER_HIKER_EARL                         477
#define TRAINER_RUIN_MANIAC_FOSTER                 478
#define TRAINER_RUIN_MANIAC_LARRY                  479
#define TRAINER_HIKER_DARYL                        480
#define TRAINER_POKEMANIAC_HECTOR                  481
#define TRAINER_PSYCHIC_DARIO                      482
#define TRAINER_PSYCHIC_RODETTE                    483
#define TRAINER_AROMA_LADY_MIAH                    484
#define TRAINER_YOUNG_COUPLE_EVE_JON               485
#define TRAINER_JUGGLER_MASON                      486
#define TRAINER_CRUSH_GIRL_CYNDY                   487
#define TRAINER_CRUSH_GIRL_JOCELYN                 488
#define TRAINER_TAMER_EVAN                         489
#define TRAINER_POKEMANIAC_MARK_2                  490
#define TRAINER_PKMN_RANGER_LOGAN                  491
#define TRAINER_PKMN_RANGER_JACKSON                492
#define TRAINER_PKMN_RANGER_BETH                   493
#define TRAINER_PKMN_RANGER_KATELYN                494
#define TRAINER_COOLTRAINER_LEROY                  495
#define TRAINER_COOLTRAINER_MICHELLE               496
#define TRAINER_COOL_COUPLE_LEX_NYA                497
#define TRAINER_RUIN_MANIAC_BRANDON                498
#define TRAINER_RUIN_MANIAC_BENJAMIN               499
#define TRAINER_PAINTER_EDNA                       500
#define TRAINER_GENTLEMAN_CLIFFORD                 501
#define TRAINER_LADY_SELPHY                        502
#define TRAINER_RUIN_MANIAC_LAWSON                 503
#define TRAINER_PSYCHIC_LAURA                      504
#define TRAINER_PKMN_BREEDER_BETHANY               505
#define TRAINER_PKMN_BREEDER_ALLISON               506
#define TRAINER_BUG_CATCHER_GARRET                 507
#define TRAINER_BUG_CATCHER_JONAH                  508
#define TRAINER_BUG_CATCHER_VANCE                  509
#define TRAINER_YOUNGSTER_NASH                     510
#define TRAINER_YOUNGSTER_CORDELL                  511
#define TRAINER_LASS_DALIA                         512
#define TRAINER_LASS_JOANA                         513
#define TRAINER_CAMPER_RILEY                       514
#define TRAINER_PICNICKER_MARCY                    515
#define TRAINER_RUIN_MANIAC_LAYTON                 516
#define TRAINER_PICNICKER_KELSEY_2                 517
#define TRAINER_PICNICKER_KELSEY_3                 518
#define TRAINER_PICNICKER_KELSEY_4                 519
#define TRAINER_CAMPER_RICKY_2                     520
#define TRAINER_CAMPER_RICKY_3                     521
#define TRAINER_CAMPER_RICKY_4                     522
#define TRAINER_CAMPER_JEFF_2                      523
#define TRAINER_CAMPER_JEFF_3                      524
#define TRAINER_CAMPER_JEFF_4                      525
#define TRAINER_PICNICKER_ISABELLE_2               526
#define TRAINER_PICNICKER_ISABELLE_3               527
#define TRAINER_PICNICKER_ISABELLE_4               528
#define TRAINER_YOUNGSTER_YASU_2                   529
#define TRAINER_YOUNGSTER_YASU_3                   530
#define TRAINER_ENGINEER_BERNIE_2                  531
#define TRAINER_GAMER_DARIAN_2                     532
#define TRAINER_CAMPER_CHRIS_2                     533
#define TRAINER_CAMPER_CHRIS_3                     534
#define TRAINER_CAMPER_CHRIS_4                     535
#define TRAINER_PICNICKER_ALICIA_2                 536
#define TRAINER_PICNICKER_ALICIA_3                 537
#define TRAINER_PICNICKER_ALICIA_4                 538
#define TRAINER_HIKER_JEREMY_2                     539
#define TRAINER_POKEMANIAC_MARK_3                  540
#define TRAINER_POKEMANIAC_HERMAN_2                541
#define TRAINER_POKEMANIAC_HERMAN_3                542
#define TRAINER_HIKER_TRENT_2                      543
#define TRAINER_LASS_MEGAN_2                       544
#define TRAINER_LASS_MEGAN_3                       545
#define TRAINER_SUPER_NERD_GLENN_2                 546
#define TRAINER_GAMER_RICH_2                       547
#define TRAINER_BIKER_JAREN_2                      548
#define TRAINER_FISHERMAN_ELLIOT_2                 549
#define TRAINER_ROCKER_LUCA_2                      550
#define TRAINER_BEAUTY_SHEILA_2                    551
#define TRAINER_BIRD_KEEPER_ROBERT_2               552
#define TRAINER_BIRD_KEEPER_ROBERT_3               553
#define TRAINER_PICNICKER_SUSIE_2                  554
#define TRAINER_PICNICKER_SUSIE_3                  555
#define TRAINER_PICNICKER_SUSIE_4                  556
#define TRAINER_BIKER_LUKAS_2                      557
#define TRAINER_BIRD_KEEPER_BENNY_2                558
#define TRAINER_BIRD_KEEPER_BENNY_3                559
#define TRAINER_BIRD_KEEPER_MARLON_2               560
#define TRAINER_BIRD_KEEPER_MARLON_3               561
#define TRAINER_BEAUTY_GRACE_2                     562
#define TRAINER_BIRD_KEEPER_CHESTER_2              563
#define TRAINER_BIRD_KEEPER_CHESTER_3              564
#define TRAINER_PICNICKER_BECKY_2                  565
#define TRAINER_PICNICKER_BECKY_3                  566
#define TRAINER_PICNICKER_BECKY_4                  567
#define TRAINER_CRUSH_KIN_RON_MYA_2                568
#define TRAINER_CRUSH_KIN_RON_MYA_3                569
#define TRAINER_CRUSH_KIN_RON_MYA_4                570
#define TRAINER_BIKER_RUBEN_2                      571
#define TRAINER_CUE_BALL_CAMRON_2                  572
#define TRAINER_BIKER_JAXON_2                      573
#define TRAINER_CUE_BALL_ISAIAH_2                  574
#define TRAINER_CUE_BALL_COREY_2                   575
#define TRAINER_BIRD_KEEPER_JACOB_2                576
#define TRAINER_BIRD_KEEPER_JACOB_3                577
#define TRAINER_SWIMMER_FEMALE_ALICE_2             578
#define TRAINER_SWIMMER_MALE_DARRIN_2              579
#define TRAINER_PICNICKER_MISSY_2                  580
#define TRAINER_PICNICKER_MISSY_3                  581
#define TRAINER_FISHERMAN_WADE_2                   582
#define TRAINER_SWIMMER_MALE_JACK_2                583
#define TRAINER_SIS_AND_BRO_LIL_IAN_2              584
#define TRAINER_SIS_AND_BRO_LIL_IAN_3              585
#define TRAINER_SWIMMER_MALE_FINN_2                586
#define TRAINER_CRUSH_GIRL_SHARON_2                587
#define TRAINER_CRUSH_GIRL_SHARON_3                588
#define TRAINER_CRUSH_GIRL_TANYA_2                 589
#define TRAINER_CRUSH_GIRL_TANYA_3                 590
#define TRAINER_BLACK_BELT_SHEA_2                  591
#define TRAINER_BLACK_BELT_SHEA_3                  592
#define TRAINER_BLACK_BELT_HUGH_2                  593
#define TRAINER_BLACK_BELT_HUGH_3                  594
#define TRAINER_CRUSH_KIN_MIK_KIA_2                595
#define TRAINER_CRUSH_KIN_MIK_KIA_3                596
#define TRAINER_TUBER_AMIRA_2                      597
#define TRAINER_TWINS_JOY_MEG_2                    598
#define TRAINER_PAINTER_RAYNA_2                    599
#define TRAINER_YOUNGSTER_DESTIN_2                 600
#define TRAINER_PKMN_BREEDER_ALIZE_2               601
#define TRAINER_YOUNG_COUPLE_GIA_JES_2             602
#define TRAINER_YOUNG_COUPLE_GIA_JES_3             603
#define TRAINER_BIRD_KEEPER_MILO_2                 604
#define TRAINER_BIRD_KEEPER_CHAZ_2                 605
#define TRAINER_BIRD_KEEPER_HAROLD_2               606
#define TRAINER_SWIMMER_FEMALE_NICOLE_2            607
#define TRAINER_PSYCHIC_JACLYN_2                   608
#define TRAINER_SWIMMER_MALE_SAMIR_2               609
#define TRAINER_HIKER_EARL_2                       610
#define TRAINER_RUIN_MANIAC_LARRY_2                611
#define TRAINER_POKEMANIAC_HECTOR_2                612
#define TRAINER_PSYCHIC_DARIO_2                    613
#define TRAINER_PSYCHIC_RODETTE_2                  614
#define TRAINER_JUGGLER_MASON_2                    615
#define TRAINER_PKMN_RANGER_NICOLAS_2              616
#define TRAINER_PKMN_RANGER_MADELINE_2             617
#define TRAINER_CRUSH_GIRL_CYNDY_2                 618
#define TRAINER_TAMER_EVAN_2                       619
#define TRAINER_PKMN_RANGER_JACKSON_2              620
#define TRAINER_PKMN_RANGER_KATELYN_2              621
#define TRAINER_COOLTRAINER_LEROY_2                622
#define TRAINER_COOLTRAINER_MICHELLE_2             623
#define TRAINER_COOL_COUPLE_LEX_NYA_2              624
#define TRAINER_BUG_CATCHER_COLTON_2               625
#define TRAINER_BUG_CATCHER_COLTON_3               626
#define TRAINER_BUG_CATCHER_COLTON_4               627
#define TRAINER_SWIMMER_MALE_MATTHEW_2             628
#define TRAINER_SWIMMER_MALE_TONY_2                629
#define TRAINER_SWIMMER_FEMALE_MELISSA_2           630
#define TRAINER_CUE_BALL_PAXTON                    631

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is
//       only space for 25 additional trainers before trainer flag space overflows.
//       MAX_TRAINERS_COUNT_FRLG can be increased but will take up additional saveblock space

#define TRAINERS_COUNT_FRLG                      632
#define MAX_TRAINERS_COUNT_FRLG                  768

#endif  // GUARD_CONSTANTS_OPPONENTS_FRLG_H
