#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#include "constants/battle_partner.h"
#include "constants/opponents_frlg.h"

#define TRAINER_NONE                        0
#define TRAINER_BRENDAN_ROUTE_103_GRASS     1
#define TRAINER_BRENDAN_RUSTBORO_GRASS      2
#define TRAINER_BRENDAN_ROUTE_110_GRASS     3
#define TRAINER_BRENDAN_ROUTE_119_GRASS     4
#define TRAINER_BRENDAN_LILYCOVE_GRASS      5
#define TRAINER_BRENDAN_ROUTE_103_FIRE      6
#define TRAINER_BRENDAN_RUSTBORO_FIRE       7
#define TRAINER_BRENDAN_ROUTE_110_FIRE      8
#define TRAINER_BRENDAN_ROUTE_119_FIRE      9
#define TRAINER_BRENDAN_LILYCOVE_FIRE      10
#define TRAINER_BRENDAN_ROUTE_103_WATER    11
#define TRAINER_BRENDAN_RUSTBORO_WATER     12
#define TRAINER_BRENDAN_ROUTE_110_WATER    13
#define TRAINER_BRENDAN_ROUTE_119_WATER    14
#define TRAINER_BRENDAN_LILYCOVE_WATER     15
#define TRAINER_MAY_ROUTE_103_GRASS        16
#define TRAINER_MAY_RUSTBORO_GRASS         17
#define TRAINER_MAY_ROUTE_110_GRASS        18
#define TRAINER_MAY_ROUTE_119_GRASS        19
#define TRAINER_MAY_LILYCOVE_GRASS         20
#define TRAINER_MAY_ROUTE_103_FIRE         21
#define TRAINER_MAY_RUSTBORO_FIRE          22
#define TRAINER_MAY_ROUTE_110_FIRE         23
#define TRAINER_MAY_ROUTE_119_FIRE         24
#define TRAINER_MAY_LILYCOVE_FIRE          25
#define TRAINER_MAY_ROUTE_103_WATER        26
#define TRAINER_MAY_RUSTBORO_WATER         27
#define TRAINER_MAY_ROUTE_110_WATER        28
#define TRAINER_MAY_ROUTE_119_WATER        29
#define TRAINER_MAY_LILYCOVE_WATER         30
#define TRAINER_WALLY_MAUVILLE             31
#define TRAINER_WALLY_VERDANTURF           32
#define TRAINER_WALLY_ROUTE_114            33
#define TRAINER_WALLY_VICTORY_ROAD_1       34
#define TRAINER_WALLY_VICTORY_ROAD_2       35
#define TRAINER_WALLY_VICTORY_ROAD_3       36
#define TRAINER_WALLY_VICTORY_ROAD_4       37
#define TRAINER_ROXANNE_1                  38
#define TRAINER_ROXANNE_2                  39
#define TRAINER_ROXANNE_3                  40
#define TRAINER_ROXANNE_4                  41
#define TRAINER_BRAWLY_1                   42
#define TRAINER_BRAWLY_2                   43
#define TRAINER_BRAWLY_3                   44
#define TRAINER_BRAWLY_4                   45
#define TRAINER_WATTSON_1                  46
#define TRAINER_WATTSON_2                  47
#define TRAINER_WATTSON_3                  48
#define TRAINER_WATTSON_4                  49
#define TRAINER_FLANNERY_1                 50
#define TRAINER_FLANNERY_2                 51
#define TRAINER_FLANNERY_3                 52
#define TRAINER_FLANNERY_4                 53
#define TRAINER_NORMAN_1                   54
#define TRAINER_NORMAN_2                   55
#define TRAINER_NORMAN_3                   56
#define TRAINER_NORMAN_4                   57
#define TRAINER_NORMAN_5                   58
#define TRAINER_WINONA_1                   59
#define TRAINER_WINONA_2                   60
#define TRAINER_WINONA_3                   61
#define TRAINER_WINONA_4                   62
#define TRAINER_TATE_AND_LIZA_1            63
#define TRAINER_TATE_AND_LIZA_2            64
#define TRAINER_TATE_AND_LIZA_3            65
#define TRAINER_TATE_AND_LIZA_4            66
#define TRAINER_JUAN_1                     67
#define TRAINER_JUAN_2                     68
#define TRAINER_JUAN_3                     69
#define TRAINER_JUAN_4                     70
#define TRAINER_SIDNEY                     71
#define TRAINER_SIDNEY_REMATCH             72
#define TRAINER_PHOEBE                     73
#define TRAINER_PHOEBE_REMATCH             74
#define TRAINER_GLACIA                     75
#define TRAINER_GLACIA_REMATCH             76
#define TRAINER_DRAKE                      77
#define TRAINER_DRAKE_REMATCH              78
#define TRAINER_WALLACE                    79
#define TRAINER_WALLACE_REMATCH            80
#define TRAINER_STEVEN                     81
#define TRAINER_GABBY_AND_TY_1             82
#define TRAINER_GABBY_AND_TY_2             83
#define TRAINER_GABBY_AND_TY_3             84
#define TRAINER_GABBY_AND_TY_4             85
#define TRAINER_GABBY_AND_TY_5             86
#define TRAINER_GABBY_AND_TY_6             87
//Route 102
#define TRAINER_CALVIN_1                   88
#define TRAINER_CALVIN_2                   89
#define TRAINER_CALVIN_3                   90
#define TRAINER_CALVIN_4                   91
#define TRAINER_CALVIN_5                   92
#define TRAINER_RICK                       93
#define TRAINER_ALLEN                      94
#define TRAINER_TIANA                      95
//Route 104 (south)
#define TRAINER_WINSTON_1                  96
#define TRAINER_WINSTON_2                  97
#define TRAINER_WINSTON_3                  98
#define TRAINER_WINSTON_4                  99
#define TRAINER_WINSTON_5                 100
#define TRAINER_BILLY                     101
#define TRAINER_DARIAN                    102
//Petalburg Woods
#define TRAINER_LYLE                      103
#define TRAINER_CASPIAN_PETALBURG_WOODS   104
#define TRAINER_JAMES_1                   105
#define TRAINER_JAMES_2                   106
#define TRAINER_JAMES_3                   107
#define TRAINER_JAMES_4                   108
#define TRAINER_JAMES_5                   109
//Route 104 (north)
#define TRAINER_CINDY_1                   110
#define TRAINER_CINDY_2                   111
#define TRAINER_CINDY_3                   112
#define TRAINER_CINDY_4                   113
#define TRAINER_CINDY_5                   114
#define TRAINER_HALEY_1                   115
#define TRAINER_HALEY_2                   116
#define TRAINER_HALEY_3                   117
#define TRAINER_HALEY_4                   118
#define TRAINER_HALEY_5                   119
#define TRAINER_GINA_AND_MIA              120
#define TRAINER_IVAN                      121
//Route 116
#define TRAINER_JOSE                      122
#define TRAINER_JOEY                      123
#define TRAINER_JANICE                    124
#define TRAINER_CLARK                     125
#define TRAINER_DEVAN                     126
#define TRAINER_JOHNSON                   127
#define TRAINER_DAWSON                    128
#define TRAINER_SARAH                     129
#define TRAINER_JERRY_1                   130
#define TRAINER_JERRY_2                   131
#define TRAINER_JERRY_3                   132
#define TRAINER_JERRY_4                   133
#define TRAINER_JERRY_5                   134
#define TRAINER_KAREN_1                   135
#define TRAINER_KAREN_2                   136
#define TRAINER_KAREN_3                   137
#define TRAINER_KAREN_4                   138
#define TRAINER_KAREN_5                   139
//Rustboro Gym
#define TRAINER_JOSH                      140
#define TRAINER_TOMMY                     141
#define TRAINER_MARCIA                    142
//Rusturf Tunnel
#define TRAINER_CASPIAN_RUSTURF_TUNNEL    143
//Route 106 (land)
#define TRAINER_NED                       144
#define TRAINER_ELLIOT_1                  145
#define TRAINER_ELLIOT_2                  146
#define TRAINER_ELLIOT_3                  147
#define TRAINER_ELLIOT_4                  148
#define TRAINER_ELLIOT_5                  149
//Dewford Gym
#define TRAINER_LAURA                     150
#define TRAINER_LILITH                    151
#define TRAINER_BRENDEN                   152
#define TRAINER_TAKAO                     153
#define TRAINER_CRISTIAN                  154
#define TRAINER_JOCELYN                   155
//Route 109 (land)
#define TRAINER_HUEY                      156
#define TRAINER_EDMOND                    157
#define TRAINER_HAILEY                    158
#define TRAINER_CHANDLER                  159
#define TRAINER_LOLA_1                    160
#define TRAINER_LOLA_2                    161
#define TRAINER_LOLA_3                    162
#define TRAINER_LOLA_4                    163
#define TRAINER_LOLA_5                    164
#define TRAINER_RICKY_1                   165
#define TRAINER_RICKY_2                   166
#define TRAINER_RICKY_3                   167
#define TRAINER_RICKY_4                   168
#define TRAINER_RICKY_5                   169
//Seashore House
#define TRAINER_SIMON                     170
#define TRAINER_JOHANNA                   171
#define TRAINER_DWAYNE                    172
//Oceanic Museum
#define TRAINER_MALIK_MUSEUM              173
#define TRAINER_MARINA_MUSEUM             174
#define TRAINER_ARCHIE_MUSEUM             175
//Route 110
#define TRAINER_ISABEL_1                  176
#define TRAINER_ISABEL_2                  177
#define TRAINER_ISABEL_3                  178
#define TRAINER_ISABEL_4                  179
#define TRAINER_ISABEL_5                  180
#define TRAINER_KALEB                     181
//Trick House 1
#define TRAINER_SALLY                     182
#define TRAINER_ROBIN                     183
#define TRAINER_EDDIE                     184
//Route 103
#define TRAINER_DAISY                     185
#define TRAINER_MARCOS                    186
#define TRAINER_RHETT                     187
#define TRAINER_AMY_AND_LIV_1             188
#define TRAINER_AMY_AND_LIV_2             189
#define TRAINER_AMY_AND_LIV_3             190
#define TRAINER_AMY_AND_LIV_4             191
#define TRAINER_AMY_AND_LIV_5             192
#define TRAINER_MIGUEL_1                  193
#define TRAINER_MIGUEL_2                  194
#define TRAINER_MIGUEL_3                  195
#define TRAINER_MIGUEL_4                  196
#define TRAINER_MIGUEL_5                  197
#define TRAINER_ANDREW                    198
//Route 110
#define TRAINER_TIMMY                     199
#define TRAINER_EDWIN_1                   200
#define TRAINER_EDWIN_2                   201
#define TRAINER_EDWIN_3                   202
#define TRAINER_EDWIN_4                   203
#define TRAINER_EDWIN_5                   204
#define TRAINER_JOSEPH                    205
#define TRAINER_EDWARD                    206
#define TRAINER_ALYSSA                    207
#define TRAINER_DALE                      208
//Route 117
#define TRAINER_DYLAN_1                   209
#define TRAINER_DYLAN_2                   210
#define TRAINER_DYLAN_3                   211
#define TRAINER_DYLAN_4                   212
#define TRAINER_DYLAN_5                   213
#define TRAINER_MARIA_1                   214
#define TRAINER_MARIA_2                   215
#define TRAINER_MARIA_3                   216
#define TRAINER_MARIA_4                   217
#define TRAINER_MARIA_5                   218
#define TRAINER_ISAAC_1                   219
#define TRAINER_ISAAC_2                   220
#define TRAINER_ISAAC_3                   221
#define TRAINER_ISAAC_4                   222
#define TRAINER_ISAAC_5                   223
#define TRAINER_LYDIA_1                   224
#define TRAINER_LYDIA_2                   225
#define TRAINER_LYDIA_3                   226
#define TRAINER_LYDIA_4                   227
#define TRAINER_LYDIA_5                   228
#define TRAINER_ANNA_AND_MEG_1            229
#define TRAINER_ANNA_AND_MEG_2            230
#define TRAINER_ANNA_AND_MEG_3            231
#define TRAINER_ANNA_AND_MEG_4            232
#define TRAINER_ANNA_AND_MEG_5            233
#define TRAINER_DEREK                     234
#define TRAINER_BRANDI                    235
#define TRAINER_MELINA                    236
#define TRAINER_AISHA                     237
//Rusturf Tunnel
#define TRAINER_MIKE                      238
//Mauville Gym
#define TRAINER_VIVIAN                    239
#define TRAINER_KIRK                      240
#define TRAINER_BEN                       241
#define TRAINER_ANGELO                    242
#define TRAINER_SHAWN                     243
//Route 118 (west)
#define TRAINER_ROSE_1                    244
#define TRAINER_ROSE_2                    245
#define TRAINER_ROSE_3                    246
#define TRAINER_ROSE_4                    247
#define TRAINER_ROSE_5                    248
#define TRAINER_DEANDRE                   249
#define TRAINER_DALTON_1                  250
#define TRAINER_DALTON_2                  251
#define TRAINER_DALTON_3                  252
#define TRAINER_DALTON_4                  253
#define TRAINER_DALTON_5                  254
#define TRAINER_WADE                      255
//Cycling Road
#define TRAINER_JACLYN                    256
#define TRAINER_ABIGAIL_1                 257
#define TRAINER_ABIGAIL_2                 258
#define TRAINER_ABIGAIL_3                 259
#define TRAINER_ABIGAIL_4                 260
#define TRAINER_ABIGAIL_5                 261
#define TRAINER_BENJAMIN_1                262
#define TRAINER_BENJAMIN_2                263
#define TRAINER_BENJAMIN_3                264
#define TRAINER_BENJAMIN_4                265
#define TRAINER_BENJAMIN_5                266
#define TRAINER_ANTHONY                   267
#define TRAINER_JASMINE                   268
#define TRAINER_JACOB                     269
//Trick House 2
#define TRAINER_TED                       270
#define TRAINER_PAUL                      271
#define TRAINER_GEORGIA                   272
//Route 111 (south)
#define TRAINER_TYRON                     273
#define TRAINER_LILY                      274
#define TRAINER_BIANCA                    275
#define TRAINER_HAYDEN                    276
#define TRAINER_VICTOR                    277
#define TRAINER_VICTORIA                  278
#define TRAINER_VIVI                      279
#define TRAINER_VICKY                     280
#define TRAINER_IRENE                     281
#define TRAINER_TRAVIS                    282
//Route 112
#define TRAINER_LARRY                     283
#define TRAINER_CAROL                     284
#define TRAINER_BRICE                     285
#define TRAINER_TRENT_1                   286
#define TRAINER_TRENT_2                   287
#define TRAINER_TRENT_3                   288
#define TRAINER_TRENT_4                   289
#define TRAINER_TRENT_5                   290
#define TRAINER_BRYANT                    291
#define TRAINER_SHAYLA                    292
//Route 111 north
#define TRAINER_WILTON_1                  293
#define TRAINER_WILTON_2                  294
#define TRAINER_WILTON_3                  295
#define TRAINER_WILTON_4                  296
#define TRAINER_WILTON_5                  297
#define TRAINER_BROOKE_1                  298
#define TRAINER_BROOKE_2                  299
#define TRAINER_BROOKE_3                  300
#define TRAINER_BROOKE_4                  301
#define TRAINER_BROOKE_5                  302
#define TRAINER_DAISUKE                   303
//Route 113
#define TRAINER_JAYLEN                    304
#define TRAINER_LAWRENCE                  305
#define TRAINER_LUNG                      306
#define TRAINER_WYATT                     307
#define TRAINER_MADELINE_1                308
#define TRAINER_MADELINE_2                309
#define TRAINER_MADELINE_3                310
#define TRAINER_MADELINE_4                311
#define TRAINER_MADELINE_5                312
#define TRAINER_TORI_AND_TIA              313
#define TRAINER_LAO_1                     314
#define TRAINER_LAO_2                     315
#define TRAINER_LAO_3                     316
#define TRAINER_LAO_4                     317
#define TRAINER_LAO_5                     318
#define TRAINER_DILLON                    319
#define TRAINER_SOPHIE                    320
#define TRAINER_COBY                      321
//Route 114
#define TRAINER_NOLAN                     322
#define TRAINER_CHARLOTTE                 323
#define TRAINER_KAI                       324
#define TRAINER_CLAUDE                    325
#define TRAINER_NANCY                     326
#define TRAINER_TYRA_AND_IVY              327
#define TRAINER_SHANE                     328
#define TRAINER_STEVE_1                   329
#define TRAINER_STEVE_2                   330
#define TRAINER_STEVE_3                   331
#define TRAINER_STEVE_4                   332
#define TRAINER_STEVE_5                   333
#define TRAINER_BERNIE_1                  334
#define TRAINER_BERNIE_2                  335
#define TRAINER_BERNIE_3                  336
#define TRAINER_BERNIE_4                  337
#define TRAINER_BERNIE_5                  338
#define TRAINER_LUCAS                     339
#define TRAINER_ANGELINA                  340
#define TRAINER_LENNY                     341
//Meteor Falls
#define TRAINER_COURTNEY_METEOR_FALLS     342
//Route 115 (south)
#define TRAINER_NOB_1                     343
#define TRAINER_NOB_2                     344
#define TRAINER_NOB_3                     345
#define TRAINER_NOB_4                     346
#define TRAINER_NOB_5                     347
#define TRAINER_HECTOR                    348
#define TRAINER_MARLENE                   349
#define TRAINER_CYNDY_1                   350
#define TRAINER_CYNDY_2                   351
#define TRAINER_CYNDY_3                   352
#define TRAINER_CYNDY_4                   353
#define TRAINER_CYNDY_5                   354
//Mt. Chimney (Magma)
#define TRAINER_GINNY_MT_CHIMNEY          355
#define TRAINER_LANDON_MT_CHIMNEY         356
#define TRAINER_TABITHA_MT_CHIMNEY        357
#define TRAINER_MAXIE_MT_CHIMNEY          358
//Jagged Pass
#define TRAINER_ERIC                      359
#define TRAINER_TERRANCE_JAGGED_PASS      360
#define TRAINER_DIANA_1                   361
#define TRAINER_DIANA_2                   362
#define TRAINER_DIANA_3                   363
#define TRAINER_DIANA_4                   364
#define TRAINER_DIANA_5                   365
#define TRAINER_AUTUMN                    366
#define TRAINER_JULIO                     367
#define TRAINER_ETHAN_1                   368
#define TRAINER_ETHAN_2                   369
#define TRAINER_ETHAN_3                   370
#define TRAINER_ETHAN_4                   371
#define TRAINER_ETHAN_5                   372
//Lavaridge Gym
#define TRAINER_JEFF                      373
#define TRAINER_JACE                      374
#define TRAINER_ELI                       375
#define TRAINER_COLE                      376
#define TRAINER_GERALD                    377
#define TRAINER_AXLE                      378
#define TRAINER_KEEGAN                    379
#define TRAINER_DANIELLE                  380
//Mt. Chimney
#define TRAINER_SHIRLEY                   381
#define TRAINER_SHEILA                    382
#define TRAINER_SHELBY_1                  383
#define TRAINER_SHELBY_2                  384
#define TRAINER_SHELBY_3                  385
#define TRAINER_SHELBY_4                  386
#define TRAINER_SHELBY_5                  387
#define TRAINER_SAWYER_1                  388
#define TRAINER_SAWYER_2                  389
#define TRAINER_SAWYER_3                  390
#define TRAINER_SAWYER_4                  391
#define TRAINER_SAWYER_5                  392
#define TRAINER_MELISSA                   393
//Route 111 (desert)
#define TRAINER_HEIDI                     394
#define TRAINER_BEAU                      395
#define TRAINER_DREW                      396
#define TRAINER_BECKY                     397
#define TRAINER_DUSTY_1                   398
#define TRAINER_DUSTY_2                   399
#define TRAINER_DUSTY_3                   400
#define TRAINER_DUSTY_4                   401
#define TRAINER_DUSTY_5                   402
#define TRAINER_CELIA                     403
#define TRAINER_BRYAN                     404
#define TRAINER_BRANDEN                   405
//Trick House 3
#define TRAINER_JUSTIN                    406
#define TRAINER_MARTHA                    407
#define TRAINER_ALAN                      408
//Petalburg Gym
#define TRAINER_RANDALL                   409
#define TRAINER_MARY                      410
#define TRAINER_PARKER                    411
#define TRAINER_ALEXIA                    412
#define TRAINER_GEORGE                    413
#define TRAINER_JODY                      414
#define TRAINER_BERKE                     415
//Route 103 (water)
#define TRAINER_ISABELLE                  416
#define TRAINER_PETE                      417
//Route 115 (north)
#define TRAINER_JAIDEN                    418
#define TRAINER_TIMOTHY_1                 419
#define TRAINER_TIMOTHY_2                 420
#define TRAINER_TIMOTHY_3                 421
#define TRAINER_TIMOTHY_4                 422
#define TRAINER_TIMOTHY_5                 423
#define TRAINER_KYRA                      424
#define TRAINER_KOICHI                    425
#define TRAINER_HELENE                    426
#define TRAINER_ALIX                      427
//Route 105
#define TRAINER_IMANI                     428
#define TRAINER_DOMINIK                   429
#define TRAINER_FOSTER                    430
#define TRAINER_BEVERLY                   431
#define TRAINER_ANDRES_1                  432
#define TRAINER_ANDRES_2                  433
#define TRAINER_ANDRES_3                  434
#define TRAINER_ANDRES_4                  435
#define TRAINER_ANDRES_5                  436
#define TRAINER_JOSUE                     437
#define TRAINER_LUIS                      438
//Route 106 (water)
#define TRAINER_DOUGLAS                   439
#define TRAINER_KYLA                      440
//Route 107
#define TRAINER_DENISE                    441
#define TRAINER_TONY_1                    442
#define TRAINER_TONY_2                    443
#define TRAINER_TONY_3                    444
#define TRAINER_TONY_4                    445
#define TRAINER_TONY_5                    446
#define TRAINER_LISA_AND_RAY              447
#define TRAINER_DARRIN                    448
#define TRAINER_BETH                      449
#define TRAINER_CAMRON                    450
//Route 108
#define TRAINER_MISSY                     451
#define TRAINER_MATTHEW                   452
#define TRAINER_TARA                      453
#define TRAINER_CAROLINA                  454
#define TRAINER_CORY_1                    455
#define TRAINER_CORY_2                    456
#define TRAINER_CORY_3                    457
#define TRAINER_CORY_4                    458
#define TRAINER_CORY_5                    459
#define TRAINER_JEROME                    460
//Abandoned Ship
#define TRAINER_THALIA_1                  461
#define TRAINER_THALIA_2                  462
#define TRAINER_THALIA_3                  463
#define TRAINER_THALIA_4                  464
#define TRAINER_THALIA_5                  465
#define TRAINER_DEMETRIUS                 466
#define TRAINER_DUNCAN                    467
#define TRAINER_CHARLIE                   468
#define TRAINER_GARRISON                  469
#define TRAINER_JANI                      470
#define TRAINER_KIRA_AND_DAN_1            471
#define TRAINER_KIRA_AND_DAN_2            472
#define TRAINER_KIRA_AND_DAN_3            473
#define TRAINER_KIRA_AND_DAN_4            474
#define TRAINER_KIRA_AND_DAN_5            475
//Route 109 (water)
#define TRAINER_AUSTINA                   476
#define TRAINER_GWEN                      477
#define TRAINER_DAVID                     478
#define TRAINER_ALICE                     479
#define TRAINER_CARTER                    480
#define TRAINER_ELIJAH                    481
#define TRAINER_MEL_AND_PAUL              482
//Trick House 4
#define TRAINER_YUJI                      483
#define TRAINER_CORA                      484
#define TRAINER_PAULA                     485
//Route 118 (east)
#define TRAINER_BARNY                     486
#define TRAINER_CHESTER                   487
#define TRAINER_PERRY                     488
//Route 123 (west)
#define TRAINER_DAVIS                     489
#define TRAINER_JAZMYN                    490
#define TRAINER_VIOLET                    491
#define TRAINER_MIU_AND_YUKI              492
//Route 119 (south)
#define TRAINER_KENT                      493
#define TRAINER_DONALD                    494
#define TRAINER_GREG                      495
#define TRAINER_TAYLOR                    496
#define TRAINER_DOUG                      497
#define TRAINER_BRENT                     498
#define TRAINER_CHRIS                     499
#define TRAINER_CATHERINE_1               500
#define TRAINER_CATHERINE_2               501
#define TRAINER_CATHERINE_3               502
#define TRAINER_CATHERINE_4               503
#define TRAINER_CATHERINE_5               504
#define TRAINER_JACKSON_1                 505
#define TRAINER_JACKSON_2                 506
#define TRAINER_JACKSON_3                 507
#define TRAINER_JACKSON_4                 508
#define TRAINER_JACKSON_5                 509
#define TRAINER_RACHEL                    510
#define TRAINER_PHIL                      511
#define TRAINER_TAKASHI                   512
#define TRAINER_DAYTON                    513
#define TRAINER_HUGH                      514
//Weather Institute
#define TRAINER_NERISSA_WEATHER_INSTITUTE 515
#define TRAINER_BERYL_WEATHER_INSTITUTE   516
#define TRAINER_MALIK_WEATHER_INSTITUTE   517
#define TRAINER_MARINA_WEATHER_INSTITUTE  518
#define TRAINER_CASPIAN_WEATHER_INSTITUTE 519
#define TRAINER_SHELLY_WEATHER_INSTITUTE  520
//Route 119 (north)
#define TRAINER_FABIAN                    521
#define TRAINER_YASU                      522
#define TRAINER_HIDEO                     523
//Route 120 (north)
#define TRAINER_CLARISSA                  524
#define TRAINER_ROBERT_1                  525
#define TRAINER_ROBERT_2                  526
#define TRAINER_ROBERT_3                  527
#define TRAINER_ROBERT_4                  528
#define TRAINER_ROBERT_5                  529
//Fortree Gym
#define TRAINER_HUMBERTO                  530
#define TRAINER_JARED                     531
#define TRAINER_ASHLEY                    532
#define TRAINER_FLINT                     533
#define TRAINER_EDWARDO                   534
#define TRAINER_DARIUS                    535
//Route 120 (south)
#define TRAINER_COLIN                     536
#define TRAINER_LEONEL                    537
#define TRAINER_ANGELICA                  538
#define TRAINER_RILEY                     539
#define TRAINER_CALLIE                    540
#define TRAINER_JENNIFER                  541
#define TRAINER_JENNA                     542
#define TRAINER_LORENZO                   543
#define TRAINER_JEFFREY_1                 544
#define TRAINER_JEFFREY_2                 545
#define TRAINER_JEFFREY_3                 546
#define TRAINER_JEFFREY_4                 547
#define TRAINER_JEFFREY_5                 548
#define TRAINER_KEIGO                     549
#define TRAINER_CHIP                      550
//Route 121
#define TRAINER_CALE                      551
#define TRAINER_TAMMY                     552
#define TRAINER_JESSICA_1                 553
#define TRAINER_JESSICA_2                 554
#define TRAINER_JESSICA_3                 555
#define TRAINER_JESSICA_4                 556
#define TRAINER_JESSICA_5                 557
#define TRAINER_KATE_AND_JOY              558
#define TRAINER_PAT                       559
#define TRAINER_MYLES                     560
#define TRAINER_WALTER_1                  561
#define TRAINER_WALTER_2                  562
#define TRAINER_WALTER_3                  563
#define TRAINER_WALTER_4                  564
#define TRAINER_WALTER_5                  565
#define TRAINER_VANESSA                   566
#define TRAINER_MARCEL                    567
#define TRAINER_CRISTIN_1                 568
#define TRAINER_CRISTIN_2                 569
#define TRAINER_CRISTIN_3                 570
#define TRAINER_CRISTIN_4                 571
#define TRAINER_CRISTIN_5                 572
//Mt. Pyre
#define TRAINER_MARK                      573
#define TRAINER_LEAH                      574
#define TRAINER_ZANDER                    575
#define TRAINER_DEZ_AND_LUKE              576
#define TRAINER_KAYLA                     577
#define TRAINER_GABRIELLE_1               578
#define TRAINER_GABRIELLE_2               579
#define TRAINER_GABRIELLE_3               580
#define TRAINER_GABRIELLE_4               581
#define TRAINER_GABRIELLE_5               582
#define TRAINER_WILLIAM                   583
#define TRAINER_TASHA                     584
#define TRAINER_ATSUSHI                   585
#define TRAINER_VALERIE_1                 586
#define TRAINER_VALERIE_2                 587
#define TRAINER_VALERIE_3                 588
#define TRAINER_VALERIE_4                 589
#define TRAINER_VALERIE_5                 590
#define TRAINER_CEDRIC                    591
#define TRAINER_NERISSA_MT_PYRE           592
#define TRAINER_BERYL_MT_PYRE             593
#define TRAINER_MALIK_MT_PYRE             594
#define TRAINER_MARINA_MT_PYRE            595
//Route 123 (east)
#define TRAINER_CAMERON_1                 596
#define TRAINER_CAMERON_2                 597
#define TRAINER_CAMERON_3                 598
#define TRAINER_CAMERON_4                 599
#define TRAINER_CAMERON_5                 600
#define TRAINER_JONAS                     601
#define TRAINER_KAYLEY                    602
#define TRAINER_KINDRA                    603
#define TRAINER_ED                        604
#define TRAINER_WENDY                     605
#define TRAINER_BRAXTON                   606
#define TRAINER_FERNANDO_1                607
#define TRAINER_FERNANDO_2                608
#define TRAINER_FERNANDO_3                609
#define TRAINER_FERNANDO_4                610
#define TRAINER_FERNANDO_5                611
#define TRAINER_ALBERTO                   612
#define TRAINER_JACKI_1                   613
#define TRAINER_JACKI_2                   614
#define TRAINER_JACKI_3                   615
#define TRAINER_JACKI_4                   616
#define TRAINER_JACKI_5                   617
#define TRAINER_FREDRICK                  618
//Magma Hideout
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1     619
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2     620
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3     621
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4     622
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5     623
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6     624
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7     625
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8     626
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9     627
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10    628
#define TRAINER_WALKER_MAGMA_HIDEOUT      629
#define TRAINER_GAETANO_MAGMA_HIDEOUT     630
#define TRAINER_JORDAN_MAGMA_HIDEOUT      631
#define TRAINER_TERRANCE_MAGMA_HIDEOUT    632
#define TRAINER_GINNY_MAGMA_HIDEOUT       633
#define TRAINER_LANDON_MAGMA_HIDEOUT      634
#define TRAINER_TABITHA_MAGMA_HIDEOUT     635
#define TRAINER_MAXIE_MAGMA_HIDEOUT       636
//Aqua Hideout
#define TRAINER_GRUNT_AQUA_HIDEOUT_1      637
#define TRAINER_GRUNT_AQUA_HIDEOUT_2      638
#define TRAINER_GRUNT_AQUA_HIDEOUT_3      639
#define TRAINER_NERISSA_AQUA_HIDEOUT      640
#define TRAINER_BERYL_AQUA_HIDEOUT        641
#define TRAINER_CASPIAN_AQUA_HIDEOUT      642
#define TRAINER_MALIK_AQUA_HIDEOUT        643
#define TRAINER_MARINA_AQUA_HIDEOUT       644
#define TRAINER_MATT_AQUA_HIDEOUT         645
//Route 124
#define TRAINER_GRACE                     646
#define TRAINER_DECLAN                    647
#define TRAINER_LILA_AND_ROY_1            648
#define TRAINER_LILA_AND_ROY_2            649
#define TRAINER_LILA_AND_ROY_3            650
#define TRAINER_LILA_AND_ROY_4            651
#define TRAINER_LILA_AND_ROY_5            652
#define TRAINER_SPENCER                   653
#define TRAINER_JENNY_1                   654
#define TRAINER_JENNY_2                   655
#define TRAINER_JENNY_3                   656
#define TRAINER_JENNY_4                   657
#define TRAINER_JENNY_5                   658
#define TRAINER_CHAD                      659
#define TRAINER_ISABELLA                  660
#define TRAINER_ROLAND                    661
//Route 125
#define TRAINER_ERNEST_1                  662
#define TRAINER_ERNEST_2                  663
#define TRAINER_ERNEST_3                  664
#define TRAINER_ERNEST_4                  665
#define TRAINER_ERNEST_5                  666
#define TRAINER_NOLEN                     667
#define TRAINER_SHARON                    668
#define TRAINER_TANYA                     669
#define TRAINER_PRESLEY                   670
#define TRAINER_AURON                     671
#define TRAINER_STAN                      672
#define TRAINER_KIM_AND_IRIS              673
//Mossdeep Gym
#define TRAINER_PRESTON                   674
#define TRAINER_MAURA                     675
#define TRAINER_SAMANTHA                  676
#define TRAINER_BLAKE                     677
#define TRAINER_MACEY                     678
#define TRAINER_CLIFFORD                  679
#define TRAINER_KATHLEEN                  680
#define TRAINER_NICHOLAS                  681
#define TRAINER_NATE                      682
#define TRAINER_VIRGIL                    683
#define TRAINER_SYLVIA                    684
#define TRAINER_HANNAH                    685
//Trick House 6
#define TRAINER_SOPHIA                    686
#define TRAINER_SEBASTIAN                 687
#define TRAINER_BENNY                     688
//Space Center
#define TRAINER_JORDAN_SPACE_CENTER       689
#define TRAINER_WALKER_SPACE_CENTER       690
#define TRAINER_GAETANO_SPACE_CENTER      691
#define TRAINER_TERRANCE_SPACE_CENTER     692
#define TRAINER_GINNY_SPACE_CENTER        693
#define TRAINER_LANDON_SPACE_CENTER       694
#define TRAINER_COURTNEY_SPACE_CENTER     695
#define TRAINER_TABITHA_SPACE_CENTER      696
#define TRAINER_MAXIE_SPACE_CENTER        697
//Route 127
#define TRAINER_AIDAN                     698
#define TRAINER_ATHENA                    699
#define TRAINER_JONAH                     700
#define TRAINER_ROGER                     701
#define TRAINER_HENRY                     702
#define TRAINER_CAMDEN                    703
#define TRAINER_KOJI_1                    704
#define TRAINER_KOJI_2                    705
#define TRAINER_KOJI_3                    706
#define TRAINER_KOJI_4                    707
#define TRAINER_KOJI_5                    708
#define TRAINER_DONNY                     709
//Route 126
#define TRAINER_LEONARDO                  710
#define TRAINER_ISOBEL                    711
#define TRAINER_DEAN                      712
#define TRAINER_NIKKI                     713
#define TRAINER_BARRY                     714
#define TRAINER_SIENNA                    715
#define TRAINER_PABLO_1                   716
#define TRAINER_PABLO_2                   717
#define TRAINER_PABLO_3                   718
#define TRAINER_PABLO_4                   719
#define TRAINER_PABLO_5                   720
#define TRAINER_BRENDA                    721
//Route 128
#define TRAINER_RUBEN                     722
#define TRAINER_ALEXA                     723
#define TRAINER_WAYNE                     724
#define TRAINER_ISAIAH_1                  725
#define TRAINER_ISAIAH_2                  726
#define TRAINER_ISAIAH_3                  727
#define TRAINER_ISAIAH_4                  728
#define TRAINER_ISAIAH_5                  729
#define TRAINER_KATELYN_1                 730
#define TRAINER_KATELYN_2                 731
#define TRAINER_KATELYN_3                 732
#define TRAINER_KATELYN_4                 733
#define TRAINER_KATELYN_5                 734
#define TRAINER_CARLEE                    735
#define TRAINER_HARRISON                  736
//Seafloor Cavern
#define TRAINER_NERISSA_SEAFLOOR_CAVERN   737
#define TRAINER_BERYL_SEAFLOOR_CAVERN     738
#define TRAINER_MALIK_SEAFLOOR_CAVERN     739
#define TRAINER_MARINA_SEAFLOOR_CAVERN    740
#define TRAINER_MATT_SEAFLOOR_CAVERN      741
#define TRAINER_SHELLY_SEAFLOOR_CAVERN    742
#define TRAINER_ARCHIE_SEAFLOOR_CAVERN    743
//Route 129
#define TRAINER_REED                      744
#define TRAINER_CHASE                     745
#define TRAINER_ALLISON                   746
#define TRAINER_CLARENCE                  747
#define TRAINER_TISHA                     748
//Route 130
#define TRAINER_RODNEY                    749
#define TRAINER_KATIE                     750
#define TRAINER_SANTIAGO                  751
//Route 131
#define TRAINER_KEVIN                     752
#define TRAINER_TALIA                     753
#define TRAINER_RICHARD                   754
#define TRAINER_KARA                      755
#define TRAINER_HERMAN                    756
#define TRAINER_SUSIE                     757
#define TRAINER_RELI_AND_IAN              758
//Route 132
#define TRAINER_GILBERT                   759
#define TRAINER_DANA                      760
#define TRAINER_RONALD                    761
#define TRAINER_KIYO                      762
#define TRAINER_PAXTON                    763
#define TRAINER_DARCY                     764
#define TRAINER_MAKAYLA                   765
#define TRAINER_JONATHAN                  766
//Route 133
#define TRAINER_LINDA                     767
#define TRAINER_BECK                      768
#define TRAINER_CONOR                     769
#define TRAINER_MOLLIE                    770
#define TRAINER_WARREN                    771
#define TRAINER_DEBRA                     772
#define TRAINER_FRANKLIN                  773
//Route 134
#define TRAINER_LAUREL                    774
#define TRAINER_JACK                      775
#define TRAINER_HITOSHI                   776
#define TRAINER_REYNA                     777
#define TRAINER_HUDSON                    778
#define TRAINER_AARON                     779
#define TRAINER_MARLEY                    780
#define TRAINER_ALEX                      781
#define TRAINER_KELVIN                    782
//Sootopolis Gym
#define TRAINER_CONNIE                    783
#define TRAINER_ANDREA                    784
#define TRAINER_DAPHNE                    785
#define TRAINER_ANNIKA                    786
#define TRAINER_TIFFANY                   787
#define TRAINER_CRISSY                    788
#define TRAINER_BETHANY                   789
#define TRAINER_OLIVIA                    790
#define TRAINER_BRIANNA                   791
#define TRAINER_BRIDGET                   792
//Trick House 7
#define TRAINER_JOSHUA                    793
#define TRAINER_PATRICIA                  794
#define TRAINER_MARIELA                   795
#define TRAINER_EVERETT                   796
#define TRAINER_ALEXIS                    797
#define TRAINER_ALVARO                    798
//Meteor Falls (Waterfall)
#define TRAINER_JOHN_AND_JAY_1            799
#define TRAINER_JOHN_AND_JAY_2            800
#define TRAINER_JOHN_AND_JAY_3            801
#define TRAINER_JOHN_AND_JAY_4            802
#define TRAINER_JOHN_AND_JAY_5            803
#define TRAINER_NICOLAS_1                 804
#define TRAINER_NICOLAS_2                 805
#define TRAINER_NICOLAS_3                 806
#define TRAINER_NICOLAS_4                 807
#define TRAINER_NICOLAS_5                 808
//Victory Road
#define TRAINER_ALBERT                    809
#define TRAINER_HOPE                      810
#define TRAINER_SHANNON                   811
#define TRAINER_SAMUEL                    812
#define TRAINER_JULIE                     813
#define TRAINER_OWEN                      814
#define TRAINER_DIANNE                    815
#define TRAINER_FELIX                     816
#define TRAINER_CAROLINE                  817
#define TRAINER_EDGAR                     818
#define TRAINER_MICHELLE                  819
#define TRAINER_MITCHELL                  820
#define TRAINER_HALLE                     821
#define TRAINER_VITO                      822
#define TRAINER_KATELYNN                  823
#define TRAINER_QUINCY                    824
//Trick House 8
#define TRAINER_KEIRA                     825
#define TRAINER_VINCENT                   826
#define TRAINER_LEROY                     827
//S.S. Tidal
#define TRAINER_LEA_AND_JED               828
#define TRAINER_GARRET                    829
#define TRAINER_MICAH                     830
#define TRAINER_COLTON                    831
#define TRAINER_NAOMI                     832
#define TRAINER_THOMAS                    833
#define TRAINER_PHILLIP                   834
#define TRAINER_LEONARD                   835
//Other
#define TRAINER_ANABEL                    836
#define TRAINER_TUCKER                    837
#define TRAINER_SPENSER                   838
#define TRAINER_GRETA                     839
#define TRAINER_NOLAND                    840
#define TRAINER_LUCY                      841
#define TRAINER_BRANDON                   842
#define TRAINER_RED                       843
#define TRAINER_LEAF                      844
#define TRAINER_BRENDAN_PLACEHOLDER       845
#define TRAINER_MAY_PLACEHOLDER           846
#define TRAINER_DUDLEY                    847
#define TRAINER_KAYLEE                    848
#define TRAINER_TERRY                     849
#define TRAINER_UNUSED_1                  850
#define TRAINER_UNUSED_2                  851
#define TRAINER_UNUSED_3                  852
#define TRAINER_UNUSED_4                  853
#define TRAINER_UNUSED_5                  854
#define TRAINER_UNUSED_6                  855
#define TRAINER_UNUSED_7                  856
#define TRAINER_UNUSED_8                  857
#define TRAINER_UNUSED_9                  858
#define TRAINER_UNUSED_10                 859
#define TRAINER_UNUSED_11                 860
#define TRAINER_UNUSED_12                 861
#define TRAINER_UNUSED_13                 862

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT_EMERALD     836
#define MAX_TRAINERS_COUNT_EMERALD 864

#if IS_FRLG
#define TRAINERS_COUNT                      TRAINERS_COUNT_FRLG
#define MAX_TRAINERS_COUNT                  MAX_TRAINERS_COUNT_FRLG
#else
#define TRAINERS_COUNT                      TRAINERS_COUNT_EMERALD
#define MAX_TRAINERS_COUNT                  MAX_TRAINERS_COUNT_EMERALD
#endif
#define TRAINER_PARTNER(partner)           (MAX_TRAINERS_COUNT + partner)

#endif  // GUARD_CONSTANTS_OPPONENTS_H
