#ifndef GUARD_CONSTANTS_WILD_ENCOUNTER_H
#define GUARD_CONSTANTS_WILD_ENCOUNTER_H

#define LAND_WILD_COUNT     10
#define WATER_WILD_COUNT    4
#define FISH_WILD_COUNT     7

#define NUM_ALTERING_CAVE_TABLES 9

#endif // GUARD_CONSTANTS_WILD_ENCOUNTER_H
