#ifndef GUARD_CONSTANTS_WILD_ENCOUNTER_H
#define GUARD_CONSTANTS_WILD_ENCOUNTER_H

#define LAND_WILD_COUNT     10
#define WATER_WILD_COUNT    4
#define FISH_WILD_COUNT     5
#define HIDDEN_WILD_COUNT   3

#define WILD_CHECK_REPEL    (1 << 0)
#define WILD_CHECK_KEEN_EYE (1 << 1)

#endif // GUARD_CONSTANTS_WILD_ENCOUNTER_H
