@@@@@ TMs @@@@@
	.align 2
SlateportCity_Market_TMs:
	.2byte ITEM_TM_WATER_PULSE
	.2byte ITEM_TM_CALM_MIND
	.2byte ITEM_TM_FALSE_SWIPE
	.2byte ITEM_TM_FIRE_SPIN
	.2byte ITEM_TM_WHIRLPOOL
	.2byte ITEM_TM_SAND_TOMB
	.2byte ITEM_TM_ACID_SPRAY
	.2byte ITEM_TM_METAL_CLAW
	.2byte ITEM_TM_SMACK_DOWN
	.2byte ITEM_TM_FLAME_CHARGE
	.2byte ITEM_TM_TRAILBLAZE
	.2byte ITEM_TM_STRUGGLE_BUG
	.2byte ITEM_TM_POUNCE
	.2byte ITEM_TM_CHILLING_WATER
	.2byte ITEM_TM_PSYCH_UP
	.2byte ITEM_TM_TRICK
	.2byte ITEM_TM_ENCORE
	.2byte ITEM_TM_HAZE
	.2byte ITEM_TM_HELPING_HAND
	pokemartlistend

	.align 2
MauvilleCity_Mart_TMs:
	.2byte ITEM_TM_CHARGE_BEAM
	.2byte ITEM_TM_VACUUM_WAVE
	.2byte ITEM_TM_ICICLE_SPEAR
	.2byte ITEM_TM_POISON_TAIL
	.2byte ITEM_TM_DRAINING_KISS
	.2byte ITEM_TM_ELECTROWEB
	.2byte ITEM_TM_ICY_WIND
	.2byte ITEM_TM_MUD_SHOT
	.2byte ITEM_TM_SNARL
	.2byte ITEM_TM_AIR_CUTTER
	.2byte ITEM_TM_PSYBEAM
	.2byte ITEM_TM_SILVER_WIND
	.2byte ITEM_TM_BUG_BITE
	.2byte ITEM_TM_BULLDOZE
	.2byte ITEM_TM_BREAKING_SWIPE
	.2byte ITEM_TM_DRAGON_TAIL
	.2byte ITEM_TM_SWIFT
	.2byte ITEM_TM_MAGICAL_LEAF
	.2byte ITEM_TM_DISARMING_VOICE
	.2byte ITEM_TM_THUNDER_FANG
	.2byte ITEM_TM_FIRE_FANG
	.2byte ITEM_TM_ICE_FANG
	.2byte ITEM_TM_THUNDER_WAVE
	.2byte ITEM_TM_WILL_O_WISP
	.2byte ITEM_TM_CONFUSE_RAY
	.2byte ITEM_TM_CHARGE
	pokemartlistend

	.align 2
LavaridgeTown_Mart_TMs:
	.2byte ITEM_TM_KNOCK_OFF
	.2byte ITEM_TM_PAYBACK
	.2byte ITEM_TM_AVALANCHE
	.2byte ITEM_TM_BRINE
	.2byte ITEM_TM_HEX
	.2byte ITEM_TM_VENOSHOCK
	.2byte ITEM_TM_U_TURN
	.2byte ITEM_TM_VOLT_SWITCH
	.2byte ITEM_TM_FLIP_TURN
	.2byte ITEM_TM_HEAT_CRASH
	.2byte ITEM_TM_HEAVY_SLAM
	.2byte ITEM_TM_SEISMIC_TOSS
	.2byte ITEM_TM_NIGHT_SHADE
	.2byte ITEM_TM_REVERSAL
	.2byte ITEM_TM_GRASS_KNOT
	.2byte ITEM_TM_GYRO_BALL
	.2byte ITEM_TM_ELECTRO_BALL
	.2byte ITEM_TM_SUPER_FANG
	.2byte ITEM_TM_FOUL_PLAY
	.2byte ITEM_TM_COUNTER
	.2byte ITEM_TM_ENDEAVOR
	.2byte ITEM_TM_FLING
	.2byte ITEM_TM_SWORDS_DANCE
	.2byte ITEM_TM_NASTY_PLOT
	.2byte ITEM_TM_IRON_DEFENSE
	.2byte ITEM_TM_AMNESIA
	.2byte ITEM_TM_AGILITY
	.2byte ITEM_TM_DRAGON_DANCE
	.2byte ITEM_TM_CHARM
	.2byte ITEM_TM_FEATHER_DANCE
	.2byte ITEM_TM_EERIE_IMPULSE
	.2byte ITEM_TM_METAL_SOUND
	.2byte ITEM_TM_FAKE_TEARS
	.2byte ITEM_TM_COACHING
	.2byte ITEM_TM_SPIKES
	.2byte ITEM_TM_TOXIC_SPIKES
	.2byte ITEM_TM_STEALTH_ROCK
	.2byte ITEM_TM_BATON_PASS
	.2byte ITEM_TM_TRICK_ROOM
	.2byte ITEM_TM_PAIN_SPLIT
	.2byte ITEM_TM_SPITE
	.2byte ITEM_TM_GRAVITY
	pokemartlistend

	.align 2
FortreeCity_Mart_TMs:
	.2byte ITEM_TM_TOXIC
	.2byte ITEM_TM_LIGHT_SCREEN
	.2byte ITEM_TM_PROTECT
	.2byte ITEM_TM_GIGA_DRAIN
	.2byte ITEM_TM_SAFEGUARD
	.2byte ITEM_TM_REFLECT
	.2byte ITEM_TM_WEATHER_BALL
	.2byte ITEM_TM_PSYCHO_CUT
	.2byte ITEM_TM_SHADOW_CLAW
	.2byte ITEM_TM_NIGHT_SLASH
	.2byte ITEM_TM_SKITTER_SMACK
	.2byte ITEM_TM_GRASSY_GLIDE
	.2byte ITEM_TM_RISING_VOLTAGE
	.2byte ITEM_TM_EXPANDING_FORCE
	.2byte ITEM_TM_SMART_STRIKE
	.2byte ITEM_TM_SCORCHING_SANDS
	.2byte ITEM_TM_BURNING_JEALOUSY
	.2byte ITEM_TM_THUNDER_PUNCH
	.2byte ITEM_TM_FIRE_PUNCH
	.2byte ITEM_TM_ICE_PUNCH
	.2byte ITEM_TM_DRAIN_PUNCH
	.2byte ITEM_TM_STOMPING_TANTRUM
	.2byte ITEM_TM_TEMPER_FLARE
	.2byte ITEM_TM_LASH_OUT
	.2byte ITEM_TM_PSYCHIC_NOISE
	.2byte ITEM_TM_SEED_BOMB
	.2byte ITEM_TM_X_SCISSOR
	.2byte ITEM_TM_SIGNAL_BEAM
	.2byte ITEM_TM_ZEN_HEADBUTT
	.2byte ITEM_TM_DRILL_RUN
	.2byte ITEM_TM_DUAL_WINGBEAT
	.2byte ITEM_TM_ICE_SPINNER
	.2byte ITEM_TM_DAZZLING_GLEAM
	.2byte ITEM_TM_ALLURING_VOICE
	.2byte ITEM_TM_MUDDY_WATER
	.2byte ITEM_TM_UPROAR
	.2byte ITEM_TM_SCALE_SHOT
	.2byte ITEM_TM_UPPER_HAND
	.2byte ITEM_TM_HARD_PRESS
	.2byte ITEM_TM_ROOST
	.2byte ITEM_TM_TAILWIND
	.2byte ITEM_TM_CURSE
	.2byte ITEM_TM_UPPER_HAND
	pokemartlistend

	.align 2
LilycoveCity_DepartmentStore_4F_Pokemart_TMs:
	.2byte ITEM_TM_BODY_SLAM
	.2byte ITEM_TM_HYPER_VOICE
	.2byte ITEM_TM_BLAZE_KICK
	.2byte ITEM_TM_HEAT_WAVE
	.2byte ITEM_TM_AQUA_TAIL
	.2byte ITEM_TM_SCALD
	.2byte ITEM_TM_PETAL_BLIZZARD
	.2byte ITEM_TM_ENERGY_BALL
	.2byte ITEM_TM_ZING_ZAP
	.2byte ITEM_TM_ICICLE_CRASH
	.2byte ITEM_TM_SKY_UPPERCUT
	.2byte ITEM_TM_AURA_SPHERE
	.2byte ITEM_TM_POISON_JAB
	.2byte ITEM_TM_SLUDGE_WAVE
	.2byte ITEM_TM_HIGH_HORSEPOWER
	.2byte ITEM_TM_EARTH_POWER
	.2byte ITEM_TM_ACROBATICS
	.2byte ITEM_TM_AIR_SLASH
	.2byte ITEM_TM_PSYCHIC_FANGS
	.2byte ITEM_TM_PSYSHOCK
	.2byte ITEM_TM_LEECH_LIFE
	.2byte ITEM_TM_LUNGE
	.2byte ITEM_TM_BUG_BUZZ
	.2byte ITEM_TM_POLLEN_PUFF
	.2byte ITEM_TM_ROCK_SLIDE
	.2byte ITEM_TM_PHANTOM_FORCE
	.2byte ITEM_TM_DRAGON_PULSE
	.2byte ITEM_TM_CRUNCH
	.2byte ITEM_TM_THROAT_CHOP
	.2byte ITEM_TM_DARK_PULSE
	.2byte ITEM_TM_IRON_HEAD
	.2byte ITEM_TM_FLASH_CANNON
	.2byte ITEM_TM_PLAY_ROUGH
	.2byte ITEM_TM_MOONBLAST
	.2byte ITEM_TM_BODY_PRESS
	.2byte ITEM_TM_FIRE_PLEDGE
	.2byte ITEM_TM_WATER_PLEDGE
	.2byte ITEM_TM_GRASS_PLEDGE
	.2byte ITEM_TM_ELECTRIC_TERRAIN
	.2byte ITEM_TM_GRASSY_TERRAIN
	.2byte ITEM_TM_PSYCHIC_TERRAIN
	.2byte ITEM_TM_MISTY_TERRAIN
	pokemartlistend

	.align 2
LilycoveCity_DepartmentStore_4F_Pokemart_StrongTMs:
	.2byte ITEM_TM_BLIZZARD
	.2byte ITEM_TM_HYPER_BEAM
	.2byte ITEM_TM_SOLAR_BEAM
	.2byte ITEM_TM_THUNDER
	.2byte ITEM_TM_FIRE_BLAST
	.2byte ITEM_TM_GIGA_IMPACT
	.2byte ITEM_TM_HYDRO_PUMP
	.2byte ITEM_TM_HURRICANE
	.2byte ITEM_TM_GUNK_SHOT
	.2byte ITEM_TM_STONE_EDGE
	.2byte ITEM_TM_BLAST_BURN
	.2byte ITEM_TM_HYDRO_CANNON
	.2byte ITEM_TM_FRENZY_PLANT
	.2byte ITEM_TM_FLARE_BLITZ
	.2byte ITEM_TM_BRAVE_BIRD
	.2byte ITEM_TM_WILD_CHARGE
	.2byte ITEM_TM_LEAF_STORM
	.2byte ITEM_TM_DRACO_METEOR
	.2byte ITEM_TM_CLOSE_COMBAT
	.2byte ITEM_TM_SOLAR_BLADE
	.2byte ITEM_TM_OUTRAGE
	.2byte ITEM_TM_FUTURE_SIGHT
	.2byte ITEM_TM_DREAM_EATER
	.2byte ITEM_TM_MISTY_EXPLOSION
	.2byte ITEM_TM_METEOR_BEAM
	.2byte ITEM_TM_STEEL_BEAM
	.2byte ITEM_TM_TRIPLE_AXEL
	.2byte ITEM_TM_POLTERGEIST
	.2byte ITEM_TM_SUPERCELL_SLAM
	pokemartlistend

@@@@@ Evolution items @@@@@
	.align 2
LilycoveCity_DepartmentStore_3F_Pokemart_Evo:
	.2byte ITEM_FIRE_STONE      @ Hoenn: Vulpix;                      Postgame: Growlithe, Growlithe-H, Unused: Cubone, Eevee, Pansear, Capsakid
	.2byte ITEM_WATER_STONE     @ Hoenn: Staryu, Lombre;              Postgame: Poliwhirl, Shellder;    Unused: Eevee, Panpour
	.2byte ITEM_THUNDER_STONE   @ Hoenn: Pikachu, Magneton, Nosepass; Postgame: Eelektrik;              Unused: Eevee, Charjabug, Tadbulb
	.2byte ITEM_LEAF_STONE      @ Hoenn: Gloom, Nuzleaf;              Postgame: Voltorb-H;              Unused: Weepinbell, Exeggcute, Eevee, Pansage, Petilil
	.2byte ITEM_MOON_STONE      @ Hoenn: Jigglypuff, Skitty;          Postgame: N/A;                    Unused: Nidorina, Nidorino, Clefairy, Eevee, Munna
	.2byte ITEM_SUN_STONE       @ Hoenn: Pikachu, Gloom;              Postgame: Sunkern, Helioptile;    Unused: Exeggcute, Eevee, Cottonee, Petilil
	.2byte ITEM_SHINY_STONE     @ Hoenn: Koffing, Roselia;            Postgame: Togetic;                Unused: Eevee, Minccino, Floette
	.2byte ITEM_DAWN_STONE      @ Hoenn: Kirlia and Snorunt
	.2byte ITEM_LINKING_CORD    @ Hoenn: Kadabra, Machoke, Graveler;  Postgame: Graveler-A;             Unused: Haunter, Boldore, Gurdurr, Karrablast, Shelmet, Phantump, Pumpkaboo
	.2byte ITEM_DRAGON_SCALE    @ Hoenn: Seadra
	.2byte ITEM_DEEP_SEA_TOOTH  @ Hoenn: Clamperl
	.2byte ITEM_DEEP_SEA_SCALE  @ Hoenn: Clamperl
	.2byte ITEM_REAPER_CLOTH    @ Hoenn: Dusclops
	.2byte ITEM_PROTECTOR       @ Hoenn: Rhydon
	.2byte ITEM_PRISM_SCALE     @ Hoenn: Feebas
	pokemartlistend

@ Unused shop that contains evo items for Pokemon not available in Emerald by default
	.align 2
LilycoveCity_DepartmentStore_3F_Pokemart_EvoUnused:
	.2byte ITEM_DUSK_STONE                         @ Unused: Murkrow, Misdreavus, Lampent, Doublade
	.2byte ITEM_ICE_STONE       @ Battle Frontier;   Postgame: Sandshrew-A, Vulpix-A; Unused: Mime Jr., Eevee, Darumaka-G, Bergmite, Crabrawler, Cetoddle
	.2byte ITEM_KINGS_ROCK      @ Battle Frontier;   Postgame: Poliwhirl and Slowpoke
	.2byte ITEM_METAL_COAT                         @ Unused: Onix and Scyther
	.2byte ITEM_BLACK_AUGURITE                     @ Unused: Scyther
	.2byte ITEM_UPGRADE                            @ Unused: Porygon
	.2byte ITEM_DUBIOUS_DISC                       @ Unused: Porygon2
	.2byte ITEM_RAZOR_FANG      @ Battle Frontier;   Postgame: Gligar
	.2byte ITEM_RAZOR_CLAW      @ Battle Frontier;   Postgame: Sneasel and Sneasel-H
	.2byte ITEM_ELECTIRIZER     @ Battle Frontier;   Postgame: Electabuzz
	.2byte ITEM_MAGMARIZER      @ Battle Frontier;   Postgame: Magmar
	.2byte ITEM_OVAL_STONE      @ Battle Frontier;   Postgame: Happiny
	.2byte ITEM_SACHET                             @ Unused: Spritzee
	.2byte ITEM_WHIPPED_DREAM                      @ Unused: Swirlix
	.2byte ITEM_GALARICA_CUFF   @ Battle Frontier;   Postgame: Slowpoke-G
	.2byte ITEM_GALARICA_WREATH @ Battle Frontier;   Postgame: Slowpoke-G
	.2byte ITEM_SWEET_APPLE                        @ Unused: Applin
	.2byte ITEM_TART_APPLE                         @ Unused: Applin
	.2byte ITEM_SYRUPY_APPLE                       @ Unused: Applin
	.2byte ITEM_CRACKED_POT                        @ Unused: Sinistea
	.2byte ITEM_CHIPPED_POT                        @ Unused: Sinistea
	.2byte ITEM_METAL_ALLOY                        @ Unused: Duraludon
	.2byte ITEM_SCROLL_OF_DARKNESS                 @ Unused: Kubfu
	.2byte ITEM_SCROLL_OF_WATERS                   @ Unused: Kubfu
	.2byte ITEM_PEAT_BLOCK      @ Battle Frontier;   Postgame: Ursaring
	.2byte ITEM_AUSPICIOUS_ARMOR                   @ Unused: Charcadet
	.2byte ITEM_MALICIOUS_ARMOR                    @ Unused: Charcadet
	.2byte ITEM_UNREMARKABLE_TEACUP                @ Unused: Poltchageist
	.2byte ITEM_MASTERPIECE_TEACUP                 @ Unused: Poltchageist
	pokemartlistend

@ Mega Stones
	.align 2
LilycoveCity_DepartmentStore_4F_Pokemart_MegaStones:
	.2byte ITEM_RAICHUNITE_X    @ 0026
	.2byte ITEM_RAICHUNITE_Y    @ 0026
	.2byte ITEM_ALAKAZITE       @ 0065
	.2byte ITEM_STARMINITE      @ 0121
	.2byte ITEM_PINSIRITE       @ 0127
	.2byte ITEM_GYARADOSITE     @ 0130
	.2byte ITEM_HERACRONITE     @ 0214
	.2byte ITEM_SKARMORITE      @ 0227
	.2byte ITEM_HOUNDOOMINITE   @ 0229
	.2byte ITEM_SCEPTILITE      @ 0254
	.2byte ITEM_BLAZIKENITE     @ 0257
	.2byte ITEM_SWAMPERTITE     @ 0260
	.2byte ITEM_GARDEVOIRITE    @ 0282
	.2byte ITEM_GALLADITE       @ 0282
	.2byte ITEM_SABLENITE       @ 0302
	.2byte ITEM_MAWILITE        @ 0303
	.2byte ITEM_AGGRONITE       @ 0306
	.2byte ITEM_MEDICHAMITE     @ 0308
	.2byte ITEM_MANECTITE       @ 0310
	.2byte ITEM_SHARPEDONITE    @ 0319
	.2byte ITEM_CAMERUPTITE     @ 0323
	.2byte ITEM_ALTARIANITE     @ 0334
	.2byte ITEM_BANETTITE       @ 0354
	.2byte ITEM_CHIMECHITE      @ 0358
	.2byte ITEM_ABSOLITE        @ 0359
	.2byte ITEM_ABSOLITE_Z      @ 0359
	.2byte ITEM_GLALITITE       @ 0362
	.2byte ITEM_FROSLASSITE     @ 0362
	.2byte ITEM_SALAMENCITE     @ 0373
	.2byte ITEM_METAGROSSITE    @ 0376
	pokemartlistend

@ Unused shop that contains Mega Stones for Pokemon not available in Emerald by default
	.align 2
LilycoveCity_DepartmentStore_4F_Pokemart_MegaStonesUnused:
	.2byte ITEM_VENUSAURITE     @ 0003
	.2byte ITEM_CHARIZARDITE_X  @ 0006
	.2byte ITEM_CHARIZARDITE_Y  @ 0006
	.2byte ITEM_BLASTOISINITE   @ 0009
	.2byte ITEM_BEEDRILLITE     @ 0015
	.2byte ITEM_PIDGEOTITE      @ 0018
	.2byte ITEM_CLEFABLITE      @ 0036
	.2byte ITEM_VICTREEBELITE   @ 0071
	.2byte ITEM_SLOWBRONITE     @ 0080
	.2byte ITEM_GENGARITE       @ 0094
	.2byte ITEM_STEELIXITE      @ 0095
	.2byte ITEM_KANGASKHANITE   @ 0115
	.2byte ITEM_SCIZORITE       @ 0123
	.2byte ITEM_AERODACTYLITE   @ 0142 Battle Frontier
	.2byte ITEM_DRAGONINITE     @ 0149
	.2byte ITEM_MEWTWONITE_X    @ 0150
	.2byte ITEM_MEWTWONITE_Y    @ 0150
	.2byte ITEM_MEGANIUMITE     @ 0154 Battle Frontier
	.2byte ITEM_FERALIGITE      @ 0160 Battle Frontier
	.2byte ITEM_AMPHAROSITE     @ 0181 Battle Frontier
	.2byte ITEM_TYRANITARITE    @ 0248
	.2byte ITEM_LATIASITE       @ 0380 Battle Frontier
	.2byte ITEM_LATIOSITE       @ 0381 Battle Frontier
	.2byte ITEM_STARAPTITE      @ 0398
	.2byte ITEM_LOPUNNITE       @ 0428
	.2byte ITEM_GARCHOMPITE     @ 0445
	.2byte ITEM_GARCHOMPITE_Z   @ 0445
	.2byte ITEM_LUCARIONITE     @ 0448
	.2byte ITEM_LUCARIONITE_Z   @ 0448
	.2byte ITEM_ABOMASITE       @ 0460
	.2byte ITEM_HEATRANITE      @ 0485
	.2byte ITEM_DARKRANITE      @ 0491
	.2byte ITEM_EMBOARITE       @ 0500
	.2byte ITEM_EXCADRITE       @ 0530 Battle Frontier
	.2byte ITEM_AUDINITE        @ 0531
	.2byte ITEM_SCOLIPITE       @ 0545
	.2byte ITEM_SCRAFTINITE     @ 0560
	.2byte ITEM_EELEKTROSSITE   @ 0604
	.2byte ITEM_CHANDELURITE    @ 0609
	.2byte ITEM_GOLURKITE       @ 0623
	.2byte ITEM_CHESNAUGHTITE   @ 0652
	.2byte ITEM_DELPHOXITE      @ 0655
	.2byte ITEM_GRENINJITE      @ 0658
	.2byte ITEM_PYROARITE       @ 0668
	.2byte ITEM_FLOETTITE       @ 0670
	.2byte ITEM_MEOWSTICITE     @ 0678
	.2byte ITEM_MALAMARITE      @ 0687
	.2byte ITEM_BARBARACITE     @ 0689
	.2byte ITEM_DRAGALGITE      @ 0691 Battle Frontier
	.2byte ITEM_HAWLUCHANITE    @ 0701
	.2byte ITEM_ZYGARDITE       @ 0718
	.2byte ITEM_DIANCITE        @ 0719
	.2byte ITEM_CRABOMINITE     @ 0740
	.2byte ITEM_GOLISOPITE      @ 0768
	.2byte ITEM_DRAMPANITE      @ 0780
	.2byte ITEM_MAGEARNITE      @ 0801
	.2byte ITEM_ZERAORITE       @ 0807
	.2byte ITEM_FALINKSITE      @ 0870
	.2byte ITEM_SCOVILLAINITE   @ 0952
	.2byte ITEM_GLIMMORANITE    @ 0970
	.2byte ITEM_TATSUGIRINITE   @ 0978
	.2byte ITEM_BAXCALIBRITE    @ 0998
	pokemartlistend

	.align 2
BattleFrontier_Mart_EvolutionMega:
	.2byte ITEM_ICE_STONE       @ Postgame: Sandshrew-A, Vulpix-A; Unused: Mime Jr., Eevee, Darumaka-G, Bergmite, Crabrawler, Cetoddle
	.2byte ITEM_KINGS_ROCK      @ Postgame: Poliwhirl, Slowpoke
	.2byte ITEM_ELECTIRIZER     @ Postgame: Electabuzz
	.2byte ITEM_MAGMARIZER      @ Postgame: Magmar
	.2byte ITEM_OVAL_STONE      @ Postgame: Happiny
	.2byte ITEM_RAZOR_FANG      @ Postgame: Gligar
	.2byte ITEM_RAZOR_CLAW      @ Postgame: Snesasel, Sneasel-H
	.2byte ITEM_GALARICA_CUFF   @ Postgame: Slowpoke-G
	.2byte ITEM_GALARICA_WREATH @ Postgame: Slowpoke-G
	.2byte ITEM_PEAT_BLOCK      @ Postgame: Ursaring
	.2byte ITEM_AERODACTYLITE   @ 0142
	.2byte ITEM_MEGANIUMITE     @ 0154
	.2byte ITEM_FERALIGITE      @ 0160
	.2byte ITEM_AMPHAROSITE     @ 0181
	.2byte ITEM_LATIASITE       @ 0380
	.2byte ITEM_LATIOSITE       @ 0381
	.2byte ITEM_EXCADRITE       @ 0530
	.2byte ITEM_DRAGALGITE      @ 0691
	.2byte ITEM_RARE_CANDY
	.2byte ITEM_EXP_CANDY_L
	.2byte ITEM_EXP_CANDY_XL
	.2byte ITEM_SACRED_ASH
	pokemartlistend

@@@@@ Other items @@@@@
	.align 2
LilycoveCity_DepartmentStore_3F_Pokemart_Mints:
	.2byte ITEM_ABILITY_CAPSULE
	.2byte ITEM_ABILITY_PATCH
	.2byte ITEM_ADAMANT_MINT
	.2byte ITEM_MODEST_MINT
	.2byte ITEM_JOLLY_MINT
	.2byte ITEM_TIMID_MINT
	.2byte ITEM_IMPISH_MINT
	.2byte ITEM_BOLD_MINT
	.2byte ITEM_CALM_MINT
	.2byte ITEM_CAREFUL_MINT
	.2byte ITEM_SERIOUS_MINT
	.2byte ITEM_LONELY_MINT
	.2byte ITEM_NAUGHTY_MINT
	.2byte ITEM_BRAVE_MINT
	.2byte ITEM_LAX_MINT
	.2byte ITEM_RELAXED_MINT
	.2byte ITEM_MILD_MINT
	.2byte ITEM_RASH_MINT
	.2byte ITEM_QUIET_MINT
	.2byte ITEM_GENTLE_MINT
	.2byte ITEM_SASSY_MINT
	.2byte ITEM_HASTY_MINT
	.2byte ITEM_NAIVE_MINT
	pokemartlistend

	.align 2
LilycoveCity_DepartmentStore_3F_Pokemart_EVs:
	.2byte ITEM_HP_UP
	.2byte ITEM_PROTEIN
	.2byte ITEM_IRON
	.2byte ITEM_CALCIUM
	.2byte ITEM_ZINC
	.2byte ITEM_CARBOS
	.2byte ITEM_POMEG_BERRY
	.2byte ITEM_KELPSY_BERRY
	.2byte ITEM_QUALOT_BERRY
	.2byte ITEM_HONDEW_BERRY
	.2byte ITEM_GREPA_BERRY
	.2byte ITEM_TAMATO_BERRY
	.2byte ITEM_X_ATTACK
	.2byte ITEM_X_DEFENSE
	.2byte ITEM_X_SP_ATK
	.2byte ITEM_X_SP_DEF
	.2byte ITEM_X_SPEED
	.2byte ITEM_X_ACCURACY
	.2byte ITEM_DIRE_HIT
	.2byte ITEM_GUARD_SPEC
	.2byte ITEM_ENERGY_POWDER
	.2byte ITEM_ENERGY_ROOT
	.2byte ITEM_HEAL_POWDER
	.2byte ITEM_REVIVAL_HERB
	pokemartlistend

	.align 2
LilycoveCity_DepartmentStore_3F_Pokemart_Delibird:
	.2byte ITEM_LEFTOVERS
	.2byte ITEM_CHOICE_BAND
	.2byte ITEM_CHOICE_SPECS
	.2byte ITEM_CHOICE_SCARF
	.2byte ITEM_WIDE_LENS
	.2byte ITEM_ZOOM_LENS
	.2byte ITEM_TOXIC_ORB
	.2byte ITEM_FLAME_ORB
	.2byte ITEM_HEAT_ROCK
	.2byte ITEM_DAMP_ROCK
	.2byte ITEM_ICY_ROCK
	.2byte ITEM_SMOOTH_ROCK
	.2byte ITEM_TERRAIN_EXTENDER
	.2byte ITEM_AIR_BALLOON
	.2byte ITEM_ASSAULT_VEST
	.2byte ITEM_BIG_ROOT
	.2byte ITEM_BLACK_SLUDGE
	.2byte ITEM_DESTINY_KNOT
	.2byte ITEM_EVIOLITE
	.2byte ITEM_LOADED_DICE
	.2byte ITEM_METRONOME
	.2byte ITEM_MIRROR_HERB
	.2byte ITEM_PUNCHING_GLOVE
	.2byte ITEM_ROCKY_HELMET
	.2byte ITEM_SCOPE_LENS
	.2byte ITEM_SHELL_BELL
	.2byte ITEM_SMOKE_BALL
	.2byte ITEM_SOOTHE_BELL
	pokemartlistend

	.align 2
BattleFrontier_Mart_HoldItem:
	.2byte ITEM_WHITE_HERB
	.2byte ITEM_MENTAL_HERB
	.2byte ITEM_POWER_HERB
	.2byte ITEM_MUSCLE_BAND
	.2byte ITEM_WISE_GLASSES
	.2byte ITEM_ELECTRIC_SEED
	.2byte ITEM_GRASSY_SEED
	.2byte ITEM_MISTY_SEED
	.2byte ITEM_PSYCHIC_SEED
	.2byte ITEM_GRIP_CLAW
	.2byte ITEM_BINDING_BAND
	.2byte ITEM_BLUNDER_POLICY
	.2byte ITEM_WEAKNESS_POLICY
	.2byte ITEM_ABILITY_SHIELD
	.2byte ITEM_ABSORB_BULB
	.2byte ITEM_ADRENALINE_ORB
	.2byte ITEM_BRIGHT_POWDER
	.2byte ITEM_CELL_BATTERY
	.2byte ITEM_CLEAR_AMULET
	.2byte ITEM_COVERT_CLOAK
	.2byte ITEM_EJECT_BUTTON
	.2byte ITEM_EJECT_PACK
	.2byte ITEM_EXPERT_BELT
	.2byte ITEM_FLOAT_STONE
	.2byte ITEM_FLYING_GEM
	.2byte ITEM_FOCUS_BAND
	.2byte ITEM_FOCUS_SASH
	.2byte ITEM_HEAVY_DUTY_BOOTS
	.2byte ITEM_IRON_BALL
	.2byte ITEM_LAGGING_TAIL
	.2byte ITEM_LIFE_ORB
	.2byte ITEM_LIGHT_CLAY
	.2byte ITEM_LUMINOUS_MOSS
	.2byte ITEM_PROTECTIVE_PADS
	.2byte ITEM_QUICK_CLAW
	.2byte ITEM_RED_CARD
	.2byte ITEM_RING_TARGET
	.2byte ITEM_ROOM_SERVICE
	.2byte ITEM_SAFETY_GOGGLES
	.2byte ITEM_SHED_SHELL
	.2byte ITEM_SNOWBALL
	.2byte ITEM_STICKY_BARB
	.2byte ITEM_THROAT_SPRAY
	.2byte ITEM_UTILITY_UMBRELLA
	pokemartlistend
